/* Generated by zi2c from compiler_text.zi. */
#ifndef ZIRAN_COMPILER_TEXT_H
#define ZIRAN_COMPILER_TEXT_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_slice.h"
#include "zir_string.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct SourceRange SourceRange;
typedef struct SourcePart SourcePart;
typedef struct DecodedLiteral DecodedLiteral;
typedef struct FormatStep FormatStep;

struct SourceRange {
    int64_t begin;
    int64_t end;
};

struct SourcePart {
    int64_t begin;
    int64_t end;
    int64_t next;
};

struct DecodedLiteral {
    bool valid;
    int64_t count;
};

struct FormatStep {
    bool valid;
    bool argument;
    bool present;
    int64_t next;
};
int32_t compiler_text_NameDistance(String a, String b, int32_t limit);
bool compiler_text_SpaceByte(uint8_t byte);
bool compiler_text_IdentifierByte(uint8_t byte);
int64_t compiler_text_SkipSpace(String source, int64_t at, bool inline_only);
SourceRange compiler_text_TrimRange(String source);
int64_t compiler_text_BlockHeaderEnd(String source);
int64_t compiler_text_CamelIdentifier(String source, Slice output);
int64_t compiler_text_GoFieldIdentifier(String source, Slice output);
int64_t compiler_text_EscapeCString(String source, Slice output);
SourcePart compiler_text_NextSourcePart(String source, int64_t at);
int64_t compiler_text_TopLevelAssignment(String source);
DecodedLiteral compiler_text_DecodeString(String source, Slice output);
FormatStep compiler_text_NextPrintPiece(Slice bytes, int64_t at, Slice output);
String compiler_text_OperatorProcedure(String op);
int64_t compiler_text_OperatorTokenLength(String source);
String compiler_text_ProcedureOperator(String name);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_TEXT_H */
