/* Generated by zi2c from compiler_text.zi. */
#include "compiler_text.h"
static uint8_t compiler_text_Byte(String source, int64_t at);
static int64_t compiler_text_AfterQuote(String source, int64_t at);
static int32_t compiler_text_HexDigit(uint8_t byte);
static int64_t compiler_text_EscapeByte(uint8_t byte, bool c_string, Slice output);
static String Operators[16] = {{"==", sizeof("==") - 1}, {"!=", sizeof("!=") - 1}, {"<=", sizeof("<=") - 1}, {">=", sizeof(">=") - 1}, {"<<", sizeof("<<") - 1}, {">>", sizeof(">>") - 1}, {"+", sizeof("+") - 1}, {"-", sizeof("-") - 1}, {"*", sizeof("*") - 1}, {"/", sizeof("/") - 1}, {"%", sizeof("%") - 1}, {"<", sizeof("<") - 1}, {">", sizeof(">") - 1}, {"&", sizeof("&") - 1}, {"|", sizeof("|") - 1}, {"^", sizeof("^") - 1}};
static String Procedures[16] = {{"operator_equal", sizeof("operator_equal") - 1}, {"operator_not_equal", sizeof("operator_not_equal") - 1}, {"operator_less_equal", sizeof("operator_less_equal") - 1}, {"operator_greater_equal", sizeof("operator_greater_equal") - 1}, {"operator_shift_left", sizeof("operator_shift_left") - 1}, {"operator_shift_right", sizeof("operator_shift_right") - 1}, {"operator_add", sizeof("operator_add") - 1}, {"operator_subtract", sizeof("operator_subtract") - 1}, {"operator_multiply", sizeof("operator_multiply") - 1}, {"operator_divide", sizeof("operator_divide") - 1}, {"operator_modulo", sizeof("operator_modulo") - 1}, {"operator_less", sizeof("operator_less") - 1}, {"operator_greater", sizeof("operator_greater") - 1}, {"operator_bit_and", sizeof("operator_bit_and") - 1}, {"operator_bit_or", sizeof("operator_bit_or") - 1}, {"operator_bit_xor", sizeof("operator_bit_xor") - 1}};

int32_t
compiler_text_NameDistance(String a, String b, int32_t limit)
{
    if (limit < 0 || limit >= 128) {
        return 128;
    }
    int64_t value_0 = (int64_t)(a).length;
    bool value_1 = value_0 >= 128LL;
    if (!value_1) {
        int64_t value_2 = (int64_t)(b).length;
        value_1 = (value_2 >= 128LL);
    }
    bool value_3 = value_1;
    if (!value_3) {
        int64_t value_4 = (int64_t)((uint64_t)((int64_t)(a).length) - (uint64_t)((int64_t)(b).length));
        int64_t value_5 = (int64_t)(limit);
        value_3 = (value_4 > value_5);
    }
    bool value_6 = value_3;
    if (!value_6) {
        int64_t value_7 = (int64_t)((uint64_t)((int64_t)(b).length) - (uint64_t)((int64_t)(a).length));
        int64_t value_8 = (int64_t)(limit);
        value_6 = (value_7 > value_8);
    }
    if (value_6) {
        return (int32_t)((uint32_t)limit + 1u);
    }
    int32_t previous[128] = {0};
    int32_t current[128] = {0};
    {
        int64_t range_first_8 = 0LL;
        int64_t range_last_8 = (int64_t)(b).length;
        int64_t j = range_first_8;
        while (j <= range_last_8) {
            ZIRAN_INDEX(previous, sizeof(previous) / sizeof(previous[0]), j) = (int32_t)(j);
            if (j == range_last_8) {
                break;
            }
            j = (int64_t)((uint64_t)j + UINT64_C(1));
        }
    }
    int64_t i = 1LL;
    while (true) {
        int64_t value_9 = (int64_t)(a).length;
        if (!(i <= value_9)) { break; }
        int32_t best = (int32_t)(i);
        ZIRAN_INDEX(current, sizeof(current) / sizeof(current[0]), 0) = best;
        int64_t j = 1LL;
        while (true) {
            int64_t value_10 = (int64_t)(b).length;
            if (!(j <= value_10)) { break; }
            bool value_11 = (uint8_t)ZIRAN_INDEX(a.data, a.length, ((int64_t)((uint64_t)i - UINT64_C(1)))) != (uint8_t)ZIRAN_INDEX(b.data, b.length, ((int64_t)((uint64_t)j - UINT64_C(1))));
            int32_t value_12 = 0;
            if (value_11) {
                value_12 = 1;
            }
            int32_t substitute = (int32_t)((uint32_t)(ZIRAN_INDEX(previous, 128, ((int64_t)((uint64_t)j - UINT64_C(1))))) + (uint32_t)value_12);
            int32_t remove = (int32_t)((uint32_t)(ZIRAN_INDEX(previous, 128, j)) + 1u);
            int32_t insert = (int32_t)((uint32_t)(ZIRAN_INDEX(current, 128, ((int64_t)((uint64_t)j - UINT64_C(1))))) + 1u);
            int32_t value = substitute;
            if (remove < value) {
                value = remove;
            }
            if (insert < value) {
                value = insert;
            }
            ZIRAN_INDEX(current, sizeof(current) / sizeof(current[0]), j) = value;
            if (value < best) {
                best = value;
            }
            j = (int64_t)((uint64_t)j + UINT64_C(1));
        }
        if (best > limit) {
            return (int32_t)((uint32_t)limit + 1u);
        }
        {
            int64_t range_first_36 = 0LL;
            int64_t range_last_36 = (int64_t)(b).length;
            int64_t j = range_first_36;
            while (j <= range_last_36) {
                ZIRAN_INDEX(previous, sizeof(previous) / sizeof(previous[0]), j) = ZIRAN_INDEX(current, 128, j);
                if (j == range_last_36) {
                    break;
                }
                j = (int64_t)((uint64_t)j + UINT64_C(1));
            }
        }
        i = (int64_t)((uint64_t)i + UINT64_C(1));
    }
    int32_t distance = ZIRAN_INDEX(previous, 128, (int64_t)(b).length);
    if (distance > limit) {
        return (int32_t)((uint32_t)limit + 1u);
    }
    return distance;
}

bool
compiler_text_SpaceByte(uint8_t byte)
{
    return byte == 32 || (byte >= 9 && byte <= 13);
}

bool
compiler_text_IdentifierByte(uint8_t byte)
{
    return (byte >= 65 && byte <= 90) || (byte >= 97 && byte <= 122) || (byte >= 48 && byte <= 57) || byte == 95;
}

int64_t
compiler_text_SkipSpace(String source, int64_t at, bool inline_only)
{
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (inline_only) {
            if (byte != 32 && byte != 9) {
                break;
            }
        } else {
            bool value_1 = compiler_text_SpaceByte(byte);
            if (!value_1) {
                break;
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return at;
}

SourceRange
compiler_text_TrimRange(String source)
{
    int64_t begin = compiler_text_SkipSpace(source, 0LL, false);
    int64_t end = (int64_t)(source).length;
    while (true) {
        bool value_0 = end > begin;
        if (value_0) {
            bool value_1 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))));
            value_0 = value_1;
        }
        if (!value_0) { break; }
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    return (SourceRange){.begin = begin, .end = end};
}

int64_t
compiler_text_BlockHeaderEnd(String source)
{
    int64_t end = (int64_t)(source).length;
    while (true) {
        bool value_0 = end > 0LL;
        if (value_0) {
            bool value_1 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))));
            value_0 = value_1;
        }
        if (!value_0) { break; }
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    bool value_2 = end > 0LL;
    if (value_2) {
        bool value_3 = (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))) == 123;
        value_2 = value_3;
    }
    if (value_2) {
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    while (true) {
        bool value_4 = end > 0LL;
        if (value_4) {
            bool value_5 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)end - UINT64_C(1)))));
            value_4 = value_5;
        }
        if (!value_4) { break; }
        end = (int64_t)((uint64_t)end - UINT64_C(1));
    }
    return end;
}

int64_t
compiler_text_CamelIdentifier(String source, Slice output)
{
    int64_t value_0 = (int64_t)(output).length;
    if (value_0 == 0LL) {
        return 0LL;
    }
    int64_t used = 0LL;
    bool upper = true;
    {
        int64_t it_index = 0LL;
        while (true) {
            int64_t value_1 = (int64_t)(source).length;
            if (!(it_index < value_1)) { break; }
            uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, it_index);
            int64_t value_2 = (int64_t)((uint64_t)used + UINT64_C(1));
            int64_t value_3 = (int64_t)(output).length;
            if (value_2 >= value_3) {
                break;
            }
            if ((byte >= 65 && byte <= 90) || (byte >= 97 && byte <= 122) || (byte >= 48 && byte <= 57)) {
                if (upper && byte >= 97 && byte <= 122) {
                    byte = (uint8_t)((uint32_t)byte - 32u);
                }
                ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = byte;
                used = (int64_t)((uint64_t)used + UINT64_C(1));
                upper = false;
            } else {
                upper = true;
            }
            it_index = (int64_t)((uint64_t)it_index + UINT64_C(1));
        }
    }
    bool value_4 = used == 0LL;
    if (value_4) {
        int64_t value_5 = (int64_t)((uint64_t)used + UINT64_C(1));
        int64_t value_6 = (int64_t)(output).length;
        value_4 = (value_5 < value_6);
    }
    if (value_4) {
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = 88;
        used = (int64_t)((uint64_t)used + UINT64_C(1));
    }
    bool value_7 = used > 0LL && ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] >= 48 && ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] <= 57;
    bool value_8 = value_7;
    if (value_8) {
        int64_t value_9 = (int64_t)((uint64_t)used + UINT64_C(1));
        int64_t value_10 = (int64_t)(output).length;
        value_8 = (value_9 < value_10);
    }
    if (value_8) {
        int64_t index = used;
        while (index > 0LL) {
            uint8_t value_11 = ((uint8_t *)output.data)[SliceIndex(output, (int64_t)((int64_t)((uint64_t)index - UINT64_C(1))))];
            ((uint8_t *)output.data)[SliceIndex(output, (int64_t)index)] = value_11;
            index = (int64_t)((uint64_t)index - UINT64_C(1));
        }
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] = 77;
        used = (int64_t)((uint64_t)used + UINT64_C(1));
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = 0;
    return used;
}

int64_t
compiler_text_GoFieldIdentifier(String source, Slice output)
{
    int64_t used = compiler_text_CamelIdentifier(source, output);
    Slice value_0 = output;
    Slice value_1 = SliceRange(value_0, (int64_t)0LL, (int64_t)used, sizeof(uint8_t));
    String name = StringView((const char *)(value_1).data, (size_t)(value_1).length);
    String replacement = StringLiteral("");
    if (StringEqual(name, StringLiteral("Id"))) {
        replacement = StringLiteral("ID");
    } else if (StringEqual(name, StringLiteral("FocusId"))) {
        replacement = StringLiteral("FocusID");
    } else if (StringEqual(name, StringLiteral("MenuId"))) {
        replacement = StringLiteral("MenuID");
    } else if (StringEqual(name, StringLiteral("SelectedId"))) {
        replacement = StringLiteral("SelectedID");
    } else if (StringEqual(name, StringLiteral("ActivatedId"))) {
        replacement = StringLiteral("ActivatedID");
    } else if (StringEqual(name, StringLiteral("CanonicalUrl"))) {
        replacement = StringLiteral("CanonicalURL");
    }
    int64_t value_2 = (int64_t)(replacement).length;
    if (value_2 == 0LL) {
        return used;
    }
    {
        int64_t range_first_24 = 0LL;
        int64_t range_last_24 = (int64_t)((uint64_t)used - UINT64_C(1));
        int64_t index = range_first_24;
        while (index <= range_last_24) {
            ((uint8_t *)output.data)[SliceIndex(output, (int64_t)index)] = (uint8_t)ZIRAN_INDEX(replacement.data, replacement.length, index);
            if (index == range_last_24) {
                break;
            }
            index = (int64_t)((uint64_t)index + UINT64_C(1));
        }
    }
    return used;
}

int64_t
compiler_text_EscapeCString(String source, Slice output)
{
    int64_t value_0 = (int64_t)(output).length;
    if (value_0 == 0LL) {
        return 0LL;
    }
    int64_t used = 0LL;
    {
        int64_t it_index = 0LL;
        while (true) {
            int64_t value_1 = (int64_t)(source).length;
            if (!(it_index < value_1)) { break; }
            uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, it_index);
            int64_t value_2 = (int64_t)((uint64_t)used + UINT64_C(1));
            int64_t value_3 = (int64_t)(output).length;
            if (value_2 >= value_3) {
                break;
            }
            uint8_t escaped[4] = {0};
            Slice value_4 = {escaped, 4};
            int64_t count = compiler_text_EscapeByte(byte, true, SliceRange(value_4, (int64_t)0, (int64_t)value_4.length, sizeof(uint8_t)));
            {
                int64_t range_first_10 = 0LL;
                int64_t range_last_10 = (int64_t)((uint64_t)count - UINT64_C(1));
                int64_t index = range_first_10;
                while (index <= range_last_10) {
                    int64_t value_5 = (int64_t)((uint64_t)used + UINT64_C(1));
                    int64_t value_6 = (int64_t)(output).length;
                    if (value_5 < value_6) {
                        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = ZIRAN_INDEX(escaped, 4, index);
                        used = (int64_t)((uint64_t)used + UINT64_C(1));
                    }
                    if (index == range_last_10) {
                        break;
                    }
                    index = (int64_t)((uint64_t)index + UINT64_C(1));
                }
            }
            it_index = (int64_t)((uint64_t)it_index + UINT64_C(1));
        }
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = 0;
    return used;
}

SourcePart
compiler_text_NextSourcePart(String source, int64_t at)
{
    bool value_0 = at < 0LL;
    if (!value_0) {
        int64_t value_1 = (int64_t)(source).length;
        value_0 = (at > value_1);
    }
    if (value_0) {
        return (SourcePart){.begin = 0LL, .end = 0LL, .next = -1LL};
    }
    int64_t start = at;
    int32_t depth = 0;
    while (true) {
        int64_t value_2 = (int64_t)(source).length;
        if (!(at < value_2)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_text_AfterQuote(source, at);
        } else if (byte == 44 && depth == 0) {
            break;
        } else {
            if (byte == 40 || byte == 91 || byte == 123) {
                depth = (int32_t)((uint32_t)depth + 1u);
            } else if (byte == 41 || byte == 93 || byte == 125) {
                if (depth > 0) {
                    depth = (int32_t)((uint32_t)depth - 1u);
                }
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    int64_t end = at;
    int64_t next = -1LL;
    int64_t value_3 = (int64_t)(source).length;
    if (at < value_3) {
        next = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    return (SourcePart){.begin = start, .end = end, .next = next};
}

int64_t
compiler_text_TopLevelAssignment(String source)
{
    int64_t at = 0LL;
    int32_t depth = 0;
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        if (byte == 34 || byte == 39) {
            at = compiler_text_AfterQuote(source, at);
        } else {
            if (byte == 40 || byte == 91 || byte == 123) {
                depth = (int32_t)((uint32_t)depth + 1u);
            } else if (byte == 41 || byte == 93 || byte == 125) {
                if (depth > 0) {
                    depth = (int32_t)((uint32_t)depth - 1u);
                }
            } else {
                bool value_1 = byte == 61 && depth == 0;
                if (value_1) {
                    bool value_2 = compiler_text_Byte(source, (int64_t)((uint64_t)at + UINT64_C(1))) != 61;
                    value_1 = value_2;
                }
                bool value_3 = value_1;
                if (value_3) {
                    bool value_4 = at == 0LL;
                    if (!value_4) {
                        bool value_5 = (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at - UINT64_C(1)))) != 61 && (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at - UINT64_C(1)))) != 33;
                        bool value_6 = value_5 && (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at - UINT64_C(1)))) != 60;
                        bool value_7 = value_6 && (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at - UINT64_C(1)))) != 62;
                        value_4 = value_7;
                    }
                    value_3 = value_4;
                }
                if (value_3) {
                    return at;
                }
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return -1LL;
}

DecodedLiteral
compiler_text_DecodeString(String source, Slice output)
{
    int64_t value_0 = (int64_t)(source).length;
    bool value_1 = value_0 < 2LL || (uint8_t)ZIRAN_INDEX(source.data, source.length, 0) != 34;
    if (!value_1) {
        bool value_2 = (uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1)))) != 34;
        value_1 = value_2;
    }
    if (value_1) {
        return (DecodedLiteral){.valid = false, .count = 0LL};
    }
    int64_t used = 0LL;
    int32_t remaining = 0;
    uint32_t scalar = 0;
    uint32_t minimum = 0;
    int64_t at = 1LL;
    while (true) {
        int64_t value_3 = (int64_t)((uint64_t)at + UINT64_C(1));
        int64_t value_4 = (int64_t)(source).length;
        if (!(value_3 < value_4)) { break; }
        uint32_t value = (uint32_t)((uint8_t)ZIRAN_INDEX(source.data, source.length, at));
        bool unicode_escape = false;
        if (value == 92) {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
            int64_t value_5 = (int64_t)((uint64_t)at + UINT64_C(1));
            int64_t value_6 = (int64_t)(source).length;
            if (value_5 >= value_6) {
                return (DecodedLiteral){.valid = false, .count = 0LL};
            }
            value = (uint32_t)((uint8_t)ZIRAN_INDEX(source.data, source.length, at));
            String escapes = StringLiteral("0abfnrtv\\\"");
            uint8_t values[10] = {0, 7, 8, 12, 10, 13, 9, 11, 92, 34};
            bool found = false;
            {
                int64_t range_first_20 = 0LL;
                int64_t range_last_20 = (int64_t)((uint64_t)((int64_t)(escapes).length) - UINT64_C(1));
                int64_t index = range_first_20;
                while (index <= range_last_20) {
                    if (value == (uint32_t)((uint8_t)ZIRAN_INDEX(escapes.data, escapes.length, index))) {
                        value = (uint32_t)(ZIRAN_INDEX(values, 10, index));
                        found = true;
                        break;
                    }
                    if (index == range_last_20) {
                        break;
                    }
                    index = (int64_t)((uint64_t)index + UINT64_C(1));
                }
            }
            if (!found) {
                if (value != 120 && value != 117 && value != 85) {
                    return (DecodedLiteral){.valid = false, .count = 0LL};
                }
                unicode_escape = value != 120;
                int32_t digits = 2;
                if (value == 117) {
                    digits = 4;
                } else if (value == 85) {
                    digits = 8;
                }
                value = 0;
                {
                    int32_t range_first_40 = 0;
                    int32_t range_last_40 = (int32_t)((uint32_t)digits - 1u);
                    int32_t index = range_first_40;
                    while (index <= range_last_40) {
                        at = (int64_t)((uint64_t)at + UINT64_C(1));
                        int64_t value_7 = (int64_t)((uint64_t)at + UINT64_C(1));
                        int64_t value_8 = (int64_t)(source).length;
                        if (value_7 >= value_8) {
                            return (DecodedLiteral){.valid = false, .count = 0LL};
                        }
                        int32_t digit = compiler_text_HexDigit((uint8_t)ZIRAN_INDEX(source.data, source.length, at));
                        if (digit < 0) {
                            return (DecodedLiteral){.valid = false, .count = 0LL};
                        }
                        value = (uint32_t)(((uint32_t)value * 16u) + (uint32_t)(digit));
                        if (index == range_last_40) {
                            break;
                        }
                        index = (int32_t)((uint32_t)index + 1u);
                    }
                }
                if (value > 1114111 || (value >= 55296 && value <= 57343)) {
                    return (DecodedLiteral){.valid = false, .count = 0LL};
                }
            }
        } else if (value == 34) {
            return (DecodedLiteral){.valid = false, .count = 0LL};
        }
        uint8_t bytes[4] = {0};
        ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 0) = (uint8_t)(value);
        int32_t count = 1;
        if (unicode_escape && value >= 128) {
            if (value < 2048) {
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 0) = (uint8_t)(((uint32_t)(192u | (uint32_t)((value >> 6)))));
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 1) = (uint8_t)(((uint32_t)(128u | ((uint32_t)value & 63u))));
                count = 2;
            } else if (value < 65536) {
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 0) = (uint8_t)(((uint32_t)(224u | (uint32_t)((value >> 12)))));
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 1) = (uint8_t)(((uint32_t)(128u | ((uint32_t)((value >> 6)) & 63u))));
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 2) = (uint8_t)(((uint32_t)(128u | ((uint32_t)value & 63u))));
                count = 3;
            } else {
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 0) = (uint8_t)(((uint32_t)(240u | (uint32_t)((value >> 18)))));
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 1) = (uint8_t)(((uint32_t)(128u | ((uint32_t)((value >> 12)) & 63u))));
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 2) = (uint8_t)(((uint32_t)(128u | ((uint32_t)((value >> 6)) & 63u))));
                ZIRAN_INDEX(bytes, sizeof(bytes) / sizeof(bytes[0]), 3) = (uint8_t)(((uint32_t)(128u | ((uint32_t)value & 63u))));
                count = 4;
            }
        }
        {
            int32_t range_first_82 = 0;
            int32_t range_last_82 = (int32_t)((uint32_t)count - 1u);
            int32_t index = range_first_82;
            while (index <= range_last_82) {
                uint8_t byte = ZIRAN_INDEX(bytes, 4, index);
                if (remaining > 0) {
                    if (((uint8_t)((uint32_t)byte & 192u)) != 128) {
                        return (DecodedLiteral){.valid = false, .count = 0LL};
                    }
                    scalar = (uint32_t)(((uint32_t)scalar << 6) | (uint32_t)(((uint8_t)((uint32_t)byte & 63u))));
                    remaining = (int32_t)((uint32_t)remaining - 1u);
                    if (remaining == 0 && (scalar < minimum || scalar > 1114111 || (scalar >= 55296 && scalar <= 57343))) {
                        return (DecodedLiteral){.valid = false, .count = 0LL};
                    }
                } else if (byte >= 128) {
                    if (byte >= 194 && byte <= 223) {
                        remaining = 1;
                        scalar = (uint32_t)(((uint8_t)((uint32_t)byte & 31u)));
                        minimum = 128;
                    } else if (byte >= 224 && byte <= 239) {
                        remaining = 2;
                        scalar = (uint32_t)(((uint8_t)((uint32_t)byte & 15u)));
                        minimum = 2048;
                    } else if (byte >= 240 && byte <= 244) {
                        remaining = 3;
                        scalar = (uint32_t)(((uint8_t)((uint32_t)byte & 7u)));
                        minimum = 65536;
                    } else {
                        return (DecodedLiteral){.valid = false, .count = 0LL};
                    }
                }
                int64_t value_9 = (int64_t)(output).length;
                if (used >= value_9) {
                    return (DecodedLiteral){.valid = false, .count = 0LL};
                }
                ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = byte;
                used = (int64_t)((uint64_t)used + UINT64_C(1));
                if (index == range_last_82) {
                    break;
                }
                index = (int32_t)((uint32_t)index + 1u);
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    if (remaining != 0) {
        return (DecodedLiteral){.valid = false, .count = 0LL};
    }
    return (DecodedLiteral){.valid = true, .count = used};
}

FormatStep
compiler_text_NextPrintPiece(Slice bytes, int64_t at, Slice output)
{
    bool value_0 = at < 0LL;
    if (!value_0) {
        int64_t value_1 = (int64_t)(bytes).length;
        value_0 = (at > value_1);
    }
    if (value_0) {
        return (FormatStep){.valid = false, .argument = false, .present = false, .next = at};
    }
    int64_t value_2 = (int64_t)(bytes).length;
    if (at == value_2) {
        return (FormatStep){.valid = true, .argument = false, .present = false, .next = at};
    }
    bool value_3 = ((uint8_t *)bytes.data)[SliceIndex(bytes, (int64_t)at)] == 37;
    if (value_3) {
        int64_t value_4 = (int64_t)((uint64_t)at + UINT64_C(1));
        int64_t value_5 = (int64_t)(bytes).length;
        bool value_6 = value_4 >= value_5;
        if (!value_6) {
            bool value_7 = ((uint8_t *)bytes.data)[SliceIndex(bytes, (int64_t)((int64_t)((uint64_t)at + UINT64_C(1))))] != 37;
            value_6 = value_7;
        }
        value_3 = value_6;
    }
    if (value_3) {
        int64_t value_8 = (int64_t)(output).length;
        if (value_8 > 0LL) {
            ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] = 0;
        }
        return (FormatStep){.valid = true, .argument = true, .present = true, .next = (int64_t)((uint64_t)at + UINT64_C(1))};
    }
    int64_t value_9 = (int64_t)(output).length;
    if (value_9 < 3LL) {
        return (FormatStep){.valid = false, .argument = false, .present = false, .next = at};
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] = 34;
    int64_t used = 1LL;
    while (true) {
        int64_t value_10 = (int64_t)(bytes).length;
        if (!(at < value_10)) { break; }
        uint8_t byte = ((uint8_t *)bytes.data)[SliceIndex(bytes, (int64_t)at)];
        if (byte == 37) {
            int64_t value_11 = (int64_t)((uint64_t)at + UINT64_C(1));
            int64_t value_12 = (int64_t)(bytes).length;
            bool value_13 = value_11 >= value_12;
            if (!value_13) {
                bool value_14 = ((uint8_t *)bytes.data)[SliceIndex(bytes, (int64_t)((int64_t)((uint64_t)at + UINT64_C(1))))] != 37;
                value_13 = value_14;
            }
            if (value_13) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
        uint8_t escaped[4] = {0};
        Slice value_15 = {escaped, 4};
        int64_t count = compiler_text_EscapeByte(byte, false, SliceRange(value_15, (int64_t)0, (int64_t)value_15.length, sizeof(uint8_t)));
        int64_t value_16 = (int64_t)(((uint64_t)used + (uint64_t)count) + UINT64_C(2));
        int64_t value_17 = (int64_t)(output).length;
        if (value_16 > value_17) {
            return (FormatStep){.valid = false, .argument = false, .present = false, .next = at};
        }
        {
            int64_t range_first_30 = 0LL;
            int64_t range_last_30 = (int64_t)((uint64_t)count - UINT64_C(1));
            int64_t index = range_first_30;
            while (index <= range_last_30) {
                ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = ZIRAN_INDEX(escaped, 4, index);
                used = (int64_t)((uint64_t)used + UINT64_C(1));
                if (index == range_last_30) {
                    break;
                }
                index = (int64_t)((uint64_t)index + UINT64_C(1));
            }
        }
        at = (int64_t)((uint64_t)at + UINT64_C(1));
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)used)] = 34;
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)((int64_t)((uint64_t)used + UINT64_C(1))))] = 0;
    return (FormatStep){.valid = true, .argument = false, .present = true, .next = at};
}

String
compiler_text_OperatorProcedure(String op)
{
    for (int64_t index = 0LL; index <= 15LL; index++) {
        if (StringEqual(op, ZIRAN_INDEX(Operators, 16, index))) {
            return ZIRAN_INDEX(Procedures, 16, index);
        }
    }
    return StringLiteral("");
}

int64_t
compiler_text_OperatorTokenLength(String source)
{
    for (int64_t index = 0LL; index <= 15LL; index++) {
        String op = ZIRAN_INDEX(Operators, 16, index);
        int64_t value_0 = (int64_t)(source).length;
        int64_t value_1 = (int64_t)(op).length;
        bool value_2 = value_0 >= value_1;
        if (value_2) {
            String value_3 = source;
            value_2 = (StringEqual(StringRange(value_3, (int64_t)0LL, (int64_t)(int64_t)(op).length), op));
        }
        if (value_2) {
            return (int64_t)(op).length;
        }
    }
    return 0LL;
}

String
compiler_text_ProcedureOperator(String name)
{
    for (int64_t index = 0LL; index <= 15LL; index++) {
        if (StringEqual(name, ZIRAN_INDEX(Procedures, 16, index))) {
            return ZIRAN_INDEX(Operators, 16, index);
        }
    }
    return StringLiteral("");
}

static uint8_t
compiler_text_Byte(String source, int64_t at)
{
    bool value_0 = at < 0LL;
    if (!value_0) {
        int64_t value_1 = (int64_t)(source).length;
        value_0 = (at >= value_1);
    }
    if (value_0) {
        return 0;
    }
    return (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
}

static int64_t
compiler_text_AfterQuote(String source, int64_t at)
{
    uint8_t quote = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
    at = (int64_t)((uint64_t)at + UINT64_C(1));
    while (true) {
        int64_t value_0 = (int64_t)(source).length;
        if (!(at < value_0)) { break; }
        uint8_t byte = (uint8_t)ZIRAN_INDEX(source.data, source.length, at);
        at = (int64_t)((uint64_t)at + UINT64_C(1));
        if (byte == quote) {
            break;
        }
        bool value_1 = byte == 92;
        if (value_1) {
            int64_t value_2 = (int64_t)(source).length;
            value_1 = (at < value_2);
        }
        if (value_1) {
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return at;
}

static int32_t
compiler_text_HexDigit(uint8_t byte)
{
    if (byte >= 48 && byte <= 57) {
        return (int32_t)((uint32_t)(byte) - 48u);
    }
    if (byte >= 97 && byte <= 102) {
        return (int32_t)(((uint32_t)(byte) - 97u) + 10u);
    }
    if (byte >= 65 && byte <= 70) {
        return (int32_t)(((uint32_t)(byte) - 65u) + 10u);
    }
    return -1;
}

static int64_t
compiler_text_EscapeByte(uint8_t byte, bool c_string, Slice output)
{
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] = 92;
    if (byte == 34 || byte == 92) {
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)1)] = byte;
        return 2LL;
    }
    if (byte == 10) {
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)1)] = 110;
        return 2LL;
    }
    if (byte == 9) {
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)1)] = 116;
        return 2LL;
    }
    if (byte == 13 && c_string) {
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)1)] = 114;
        return 2LL;
    }
    if (byte < 32 || byte == 127) {
        String hex = StringLiteral("0123456789abcdef");
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)1)] = 120;
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)2)] = (uint8_t)ZIRAN_INDEX(hex.data, hex.length, ((uint8_t)(byte >> 4)));
        ((uint8_t *)output.data)[SliceIndex(output, (int64_t)3)] = (uint8_t)ZIRAN_INDEX(hex.data, hex.length, ((uint8_t)((uint32_t)byte & 15u)));
        return 4LL;
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)0)] = byte;
    return 1LL;
}
