#!/usr/bin/env python3
"""Generate Unicode 17.0 grapheme tables and conformance cases from official UCD files.

Inputs: GraphemeBreakProperty.txt, emoji-data.txt, DerivedCoreProperties.txt,
GraphemeBreakTest.txt in a supplied directory. No downloads occur in builds.
"""
import argparse
from pathlib import Path

PROPERTIES = {name: index for index, name in enumerate(
    ('Other', 'CR', 'LF', 'Control', 'Extend', 'ZWJ', 'Regional_Indicator',
     'Prepend', 'SpacingMark', 'L', 'V', 'T', 'LV', 'LVT'))}


def records(path):
    for line in path.read_text().splitlines():
        fields = [part.strip() for part in line.split('#')[0].split(';')]
        if len(fields) < 2:
            continue
        bounds = fields[0].split('..')
        yield int(bounds[0], 16), int(bounds[-1], 16), fields[1:]


def generate(directory, root):
    values = [0] * 0x110000
    for start, end, fields in records(directory / 'GraphemeBreakProperty.txt'):
        if fields[0] in ('LV', 'LVT'):
            continue  # Hangul syllables have an arithmetic classification.
        for point in range(start, end + 1):
            values[point] |= PROPERTIES[fields[0]]
    for start, end, fields in records(directory / 'emoji-data.txt'):
        if fields[0] == 'Extended_Pictographic':
            for point in range(start, end + 1):
                values[point] |= 256
    for start, end, fields in records(directory / 'DerivedCoreProperties.txt'):
        if fields[0] == 'InCB':
            flag = {'Consonant': 512, 'Extend': 1024, 'Linker': 2048}[fields[1]]
            for point in range(start, end + 1):
                values[point] |= flag
    ranges = []
    start = 0
    for point in range(1, len(values) + 1):
        if point == len(values) or values[point] != values[start]:
            if values[start]:
                ranges.append((start, point - 1, values[start]))
            start = point
    output = ['// Generated by scripts/grapheme_data.py from Unicode 17.0.0 UCD.',
              '// Copyright Unicode, Inc. Distributed under the Unicode License V3.',
              '// https://www.unicode.org/license.txt', '']
    output.append('''Property :: (point: u32) -> s32 {
    if point >= cast(u32)44032 && point <= cast(u32)55203 {
        return ifx (point - cast(u32)44032) % cast(u32)28 == cast(u32)0 then 12 else 13
    }
''')
    # A balanced decision tree avoids module-initialization work and large
    # aggregate literals. It has the same logarithmic lookup cost on every target.
    def emit(rows, depth):
        indent = '    ' * depth
        if not rows:
            return [indent + 'return 0']
        middle = len(rows) // 2
        start, end, flags = rows[middle]
        if start == 0:
            return ([indent + f'if point > cast(u32){end} {{'] +
                    emit(rows[middle + 1:], depth + 1) +
                    [indent + f'}} else {{ return {flags} }}'])
        return ([indent + f'if point < cast(u32){start} {{'] +
                emit(rows[:middle], depth + 1) +
                [indent + f'}} else if point > cast(u32){end} {{'] +
                emit(rows[middle + 1:], depth + 1) +
                [indent + f'}} else {{ return {flags} }}'])
    output.extend(emit(ranges, 1))
    output.append('}\n')
    (root / 'std/grapheme_data.zi').write_text('\n'.join(output))
    cases = []
    for line in (directory / 'GraphemeBreakTest.txt').read_text().splitlines():
        tokens = line.split('#')[0].split()
        if not tokens:
            continue
        data = bytearray()
        offsets = []
        for token in tokens:
            if token == '÷':
                offsets.append(len(data))
            elif token != '×':
                data.extend(chr(int(token, 16)).encode('utf-8'))
        literal = ''.join(f'\\x{byte:02x}' for byte in data)
        name = f'offsets{len(cases)}'
        cases.append(f'    {name}: [{len(offsets)}]s32 = .{{{", ".join(map(str, offsets))}}}\n'
                     f'    if !Check("{literal}", {name}[:]) {{ return false }}')
    source = '''// Generated Unicode 17.0.0 GraphemeBreakTest corpus; Unicode License V3.
// https://www.unicode.org/license.txt
G :: #import "std/grapheme";
Check :: (value: string, offsets: []s32) -> bool {
        at: s32 = 0
        index: s32 = 1
        while at < cast(s32)value.count {
            at = G.Next(value, at)
            if index >= cast(s32)offsets.count || at != offsets[index] { return false }
            index += 1
        }
        if index != cast(s32)offsets.count { return false }
        index = cast(s32)offsets.count - 1
        while index > 0 {
            if G.Previous(value, offsets[index]) != offsets[index - 1] { return false }
            index -= 1
        }
    return true
}
'''
    chunks = [cases[index:index + 80] for index in range(0, len(cases), 80)]
    for index, chunk in enumerate(chunks):
        source += f'Cases{index} :: () -> bool {{\n' + '\n'.join(chunk) + '\n    return true\n}\n'
    source += '#program_export\nNativeMain :: () -> s32 {\n'
    for index in range(len(chunks)):
        source += f'    if !Cases{index}() {{ return {index + 1} }}\n'
    source += '    return 0\n}\n'
    (root / 'tests/spec/grapheme_conformance.zi').write_text(source)
    print(f'Generated {len(ranges)} property ranges and {len(cases)} official conformance cases')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('directory', type=Path)
    args = parser.parse_args()
    generate(args.directory, Path(__file__).resolve().parents[1])
