/* Generated by zi2c from compiler_expression.zi. */
#include "compiler_expression.h"
static String compiler_expression_UnarySpelling(String operator);
static String compiler_expression_TypeRange(String source, SyntaxCursor* cursor, int64_t start, int64_t limit);
static String compiler_expression_QualifiedName(Slice output, String first, String second, int64_t limit);
static bool compiler_expression_Take(SyntaxCursor* cursor, String wanted);
static void compiler_expression_Expect(SyntaxCursor* cursor, String wanted);
static String compiler_expression_BorrowToken(String source, SyntaxCursor* cursor);
static String compiler_expression_Following(String source, SyntaxCursor* cursor, int32_t distance);
static int32_t compiler_expression_Hex(uint8_t byte);
static String compiler_expression_Trim(String source);
static String compiler_expression_SkipSpace(String source);
static int64_t compiler_expression_FindByte(String source, uint8_t wanted);
static int64_t compiler_expression_FindPair(String source, String wanted);
static bool compiler_expression_WordAt(String source, int64_t at, String word);
static bool compiler_expression_AssignmentOperator(String operator);

int32_t
compiler_expression_BinaryPrecedence(String operator)
{
    if (StringEqual(operator, StringLiteral("||"))) {
        return 2;
    }
    if (StringEqual(operator, StringLiteral("&&"))) {
        return 3;
    }
    if (StringEqual(operator, StringLiteral("|"))) {
        return 4;
    }
    if (StringEqual(operator, StringLiteral("^"))) {
        return 5;
    }
    if (StringEqual(operator, StringLiteral("&"))) {
        return 6;
    }
    if (StringEqual(operator, StringLiteral("==")) || StringEqual(operator, StringLiteral("!="))) {
        return 7;
    }
    bool value_0 = StringEqual(operator, StringLiteral("<")) || StringEqual(operator, StringLiteral("<=")) || StringEqual(operator, StringLiteral(">"));
    if (value_0 || StringEqual(operator, StringLiteral(">="))) {
        return 8;
    }
    if (StringEqual(operator, StringLiteral("<<")) || StringEqual(operator, StringLiteral(">>"))) {
        return 9;
    }
    if (StringEqual(operator, StringLiteral("+")) || StringEqual(operator, StringLiteral("-"))) {
        return 10;
    }
    if (StringEqual(operator, StringLiteral("*")) || StringEqual(operator, StringLiteral("/")) || StringEqual(operator, StringLiteral("%"))) {
        return 11;
    }
    return 0;
}

String
compiler_expression_BinarySpelling(String operator)
{
    String operators[18] = {StringLiteral("||"), StringLiteral("&&"), StringLiteral("|"), StringLiteral("^"), StringLiteral("&"), StringLiteral("=="), StringLiteral("!="), StringLiteral("<"), StringLiteral("<="), StringLiteral(">"), StringLiteral(">="), StringLiteral("<<"), StringLiteral(">>"), StringLiteral("+"), StringLiteral("-"), StringLiteral("*"), StringLiteral("/"), StringLiteral("%")};
    for (int64_t it_index = 0LL; it_index < 18; it_index++) {
        String spelling = ZIRAN_INDEX(operators, 18, it_index);
        if (StringEqual(operator, spelling)) {
            return spelling;
        }
    }
    return StringLiteral("");
}

int32_t
compiler_expression_ParseBinary(ExpressionHooks* hooks, int32_t minimum)
{
    ExpressionBegin begin = hooks->begin;
    ExpressionToken token = hooks->token;
    ExpressionPrefix prefix = hooks->prefix;
    ExpressionAdvance advance = hooks->advance;
    ExpressionBinary binary = hooks->binary;
    ExpressionConditionalError conditional_error = hooks->conditional_error;
    ExpressionBegin value_0 = begin;
    int64_t start = value_0.call(value_0.context);
    ExpressionPrefix value_1 = prefix;
    int32_t left = value_1.call(value_1.context);
    (*(hooks->depth)) = (int32_t)((uint32_t)((*(hooks->depth))) + 1u);
    if (*(hooks->depth) > 128) {
        (*(hooks->failed)) = 1;
        (*(hooks->depth)) = (int32_t)((uint32_t)((*(hooks->depth))) - 1u);
        return -1;
    }
    while (*(hooks->failed) == 0) {
        ExpressionToken value_2 = token;
        String operator = compiler_expression_BinarySpelling(value_2.call(value_2.context));
        int32_t precedence = compiler_expression_BinaryPrecedence(operator);
        if (precedence == 0 || precedence < minimum) {
            break;
        }
        ExpressionAdvance value_3 = advance;
        value_3.call(value_3.context);
        int32_t right = compiler_expression_ParseBinary(hooks, (int32_t)((uint32_t)precedence + 1u));
        ExpressionBinary value_4 = binary;
        left = value_4.call(value_4.context, start, operator, left, right);
    }
    ExpressionToken value_5 = token;
    if (StringEqual(value_5.call(value_5.context), StringLiteral("\?"))) {
        ExpressionConditionalError value_6 = conditional_error;
        value_6.call(value_6.context);
    }
    (*(hooks->depth)) = (int32_t)((uint32_t)((*(hooks->depth))) - 1u);
    return left;
}

int32_t
compiler_expression_ParsePostfix(PostfixHooks* hooks, int64_t start, int32_t initial)
{
    SyntaxCursor* cursor = hooks->cursor;
    ExpressionToken token = cursor->token;
    ExpressionKind kind = cursor->kind;
    ExpressionBegin begin = cursor->begin;
    ExpressionAdvance advance = cursor->advance;
    ExpressionParse parse = cursor->parse;
    ExpressionLink link = cursor->link;
    PostfixNode node = hooks->node;
    ExpressionArgument argument = hooks->argument;
    ExpressionDefaults defaults = hooks->defaults;
    ExpressionName callee_name = hooks->name;
    PostfixDiagnostic error = hooks->error;
    int32_t result = initial;
    while (*(cursor->failed) == 0) {
        if (compiler_expression_Take(cursor, StringLiteral("["))) {
            int32_t low = -1;
            ExpressionToken value_0 = token;
            if (!StringEqual(value_0.call(value_0.context), StringLiteral(":"))) {
                ExpressionParse value_1 = parse;
                low = value_1.call(value_1.context, 1);
            }
            if (compiler_expression_Take(cursor, StringLiteral(":"))) {
                int32_t high = -1;
                ExpressionToken value_2 = token;
                if (!StringEqual(value_2.call(value_2.context), StringLiteral("]"))) {
                    ExpressionParse value_3 = parse;
                    high = value_3.call(value_3.context, 1);
                }
                compiler_expression_Expect(cursor, StringLiteral("]"));
                PostfixNode value_4 = node;
                result = value_4.call(value_4.context, start, PostfixKind_Slice, StringLiteral(""), result, low, high, -1);
            } else {
                compiler_expression_Expect(cursor, StringLiteral("]"));
                PostfixNode value_5 = node;
                result = value_5.call(value_5.context, start, PostfixKind_Index, StringLiteral(""), result, low, -1, -1);
            }
        } else {
            ExpressionToken value_6 = token;
            if (StringEqual(value_6.call(value_6.context), StringLiteral("->"))) {
                PostfixDiagnostic value_7 = error;
                value_7.call(value_7.context, PostfixError_PointerMember);
                break;
            } else if (compiler_expression_Take(cursor, StringLiteral("."))) {
                if (compiler_expression_Take(cursor, StringLiteral("*"))) {
                    PostfixNode value_8 = node;
                    result = value_8.call(value_8.context, start, PostfixKind_Dereference, StringLiteral(""), result, -1, -1, -1);
                } else {
                    ExpressionKind value_9 = kind;
                    if (((TokenKind)(value_9.call(value_9.context))) != ((TokenKind)(1))) {
                        (*(cursor->failed)) = 1;
                    }
                    String name = compiler_expression_BorrowToken(cursor->source, cursor);
                    ExpressionAdvance value_10 = advance;
                    value_10.call(value_10.context);
                    PostfixNode value_11 = node;
                    result = value_11.call(value_11.context, start, PostfixKind_Member, name, result, -1, -1, -1);
                }
            } else if (compiler_expression_Take(cursor, StringLiteral("("))) {
                int32_t first = -1;
                int32_t last = -1;
                int32_t callee = result;
                ExpressionName value_12 = callee_name;
                String name = value_12.call(value_12.context, callee);
                ExpressionToken value_13 = token;
                if ((!StringEqual(value_13.call(value_13.context), StringLiteral(")")))) {
                    while (true) {
                        String argument_name = StringLiteral("");
                        ExpressionKind value_14 = kind;
                        bool value_15 = ((TokenKind)(value_14.call(value_14.context))) == ((TokenKind)(1));
                        bool value_16 = value_15;
                        if (value_16) {
                            bool value_17 = StringEqual(compiler_expression_Following(cursor->source, cursor, 1), StringLiteral("="));
                            value_16 = value_17;
                        }
                        if (value_16) {
                            argument_name = compiler_expression_BorrowToken(cursor->source, cursor);
                            ExpressionAdvance value_18 = advance;
                            value_18.call(value_18.context);
                            compiler_expression_Expect(cursor, StringLiteral("="));
                        }
                        ExpressionParse value_19 = parse;
                        int32_t child = value_19.call(value_19.context, 1);
                        if (child < 0) {
                            (*(cursor->failed)) = 1;
                            break;
                        }
                        ExpressionArgument value_20 = argument;
                        value_20.call(value_20.context, child, argument_name);
                        if (last >= 0) {
                            ExpressionLink value_21 = link;
                            value_21.call(value_21.context, last, child);
                        } else {
                            first = child;
                        }
                        last = child;
                        bool value_22 = compiler_expression_Take(cursor, StringLiteral(","));
                        if (!value_22) {
                            break;
                        }
                    }
                }
                compiler_expression_Expect(cursor, StringLiteral(")"));
                if (*(cursor->failed) == 0) {
                    ExpressionDefaults value_23 = defaults;
                    ExpressionChildren children = value_23.call(value_23.context, callee, first, last);
                    first = children.first;
                    last = children.last;
                }
                PostfixNode value_24 = node;
                result = value_24.call(value_24.context, start, PostfixKind_Call, name, callee, -1, -1, first);
            } else {
                ExpressionToken value_25 = token;
                bool value_26 = StringEqual(value_25.call(value_25.context), StringLiteral("++"));
                bool value_27 = value_26;
                if (!value_27) {
                    ExpressionToken value_28 = token;
                    bool value_29 = StringEqual(value_28.call(value_28.context), StringLiteral("--"));
                    value_27 = value_29;
                }
                if (value_27) {
                    PostfixDiagnostic value_30 = error;
                    value_30.call(value_30.context, PostfixError_Increment);
                    break;
                } else {
                    ExpressionToken value_31 = token;
                    bool value_32 = StringEqual(value_31.call(value_31.context), StringLiteral("\?"));
                    bool value_33 = value_32;
                    if (value_33) {
                        ExpressionBegin value_34 = begin;
                        int64_t value_35 = value_34.call(value_34.context);
                        value_33 = (value_35 > 0LL);
                    }
                    bool value_36 = value_33;
                    if (value_36) {
                        ExpressionBegin value_37 = begin;
                        int64_t value_38 = value_37.call(value_37.context);
                        int64_t value_39 = (int64_t)(cursor->source).length;
                        value_36 = (value_38 <= value_39);
                    }
                    bool value_40 = value_36;
                    bool value_41 = value_40;
                    if (value_41) {
                        ExpressionBegin value_42 = begin;
                        int64_t value_43 = (int64_t)((uint64_t)(value_42.call(value_42.context)) - UINT64_C(1));
                        bool value_44 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(cursor->source.data, cursor->source.length, value_43));
                        value_41 = !value_44;
                    }
                    if (value_41) {
                        PostfixDiagnostic value_45 = error;
                        value_45.call(value_45.context, PostfixError_Question);
                        break;
                    } else {
                        break;
                    }
                }
            }
        }
    }
    return result;
}

int32_t
compiler_expression_ParseInitializer(InitializerHooks* hooks, int64_t start, String type, String open, String close)
{
    SyntaxCursor* cursor = hooks->cursor;
    ExpressionToken token = cursor->token;
    ExpressionKind kind = cursor->kind;
    ExpressionBegin begin = cursor->begin;
    ExpressionAdvance advance = cursor->advance;
    ExpressionParse parse = cursor->parse;
    ExpressionLink link = cursor->link;
    InitializerFieldType field_type = hooks->field_type;
    InitializerField field = hooks->field;
    InitializerNode node = hooks->node;
    int32_t first = -1;
    int32_t last = -1;
    int32_t ordinal = 0;
    compiler_expression_Expect(cursor, open);
    while (true) {
        bool value_0 = *(cursor->failed) == 0;
        bool value_1 = value_0;
        if (value_1) {
            ExpressionToken value_2 = token;
            bool value_3 = !StringEqual(value_2.call(value_2.context), close);
            value_1 = value_3;
        }
        bool value_4 = value_1;
        bool value_5 = value_4;
        if (value_5) {
            ExpressionKind value_6 = kind;
            bool value_7 = ((TokenKind)(value_6.call(value_6.context))) != ((TokenKind)(0));
            value_5 = value_7;
        }
        if (!value_5) { break; }
        ExpressionBegin value_8 = begin;
        int64_t field_start = value_8.call(value_8.context);
        String name = StringLiteral("");
        bool named = false;
        ExpressionToken value_9 = token;
        bool value_10 = StringEqual(value_9.call(value_9.context), StringLiteral("."));
        bool value_11 = value_10;
        if (value_11) {
            bool value_12 = StringEqual(compiler_expression_Following(cursor->source, cursor, 2), StringLiteral("="));
            value_11 = value_12;
        }
        if (value_11) {
            String value_13 = cursor->source;
            ExpressionBegin value_14 = begin;
            int64_t value_15 = value_14.call(value_14.context);
            ExpressionToken value_16 = token;
            String value_17 = value_16.call(value_16.context);
            Scan next = compiler_scan_NextToken(value_13, (int64_t)((uint64_t)value_15 + (uint64_t)((int64_t)(value_17).length)), 1, 1);
            if (((TokenKind)(next.kind)) == ((TokenKind)(1))) {
                ExpressionAdvance value_18 = advance;
                value_18.call(value_18.context);
                named = true;
            }
        }
        bool value_19 = !named;
        if (value_19) {
            ExpressionKind value_20 = kind;
            bool value_21 = ((TokenKind)(value_20.call(value_20.context))) == ((TokenKind)(1));
            value_19 = value_21;
        }
        if (value_19) {
            named = StringEqual(compiler_expression_Following(cursor->source, cursor, 1), StringLiteral("="));
        }
        if (named) {
            ExpressionKind value_22 = kind;
            if (((TokenKind)(value_22.call(value_22.context))) != ((TokenKind)(1))) {
                (*(cursor->failed)) = 1;
                break;
            }
            name = compiler_expression_BorrowToken(cursor->source, cursor);
            ExpressionAdvance value_23 = advance;
            value_23.call(value_23.context);
            compiler_expression_Expect(cursor, StringLiteral("="));
        }
        int32_t value = -1;
        ExpressionToken value_24 = token;
        if (StringEqual(value_24.call(value_24.context), StringLiteral("{"))) {
            InitializerFieldType value_25 = field_type;
            String nested_type = value_25.call(value_25.context, type, name, ordinal);
            (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) + 1u);
            if (*(cursor->depth) > 128) {
                (*(cursor->failed)) = 1;
                (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) - 1u);
                return -1;
            }
            ExpressionBegin value_26 = begin;
            value = compiler_expression_ParseInitializer(hooks, value_26.call(value_26.context), nested_type, StringLiteral("{"), StringLiteral("}"));
            (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) - 1u);
        } else {
            ExpressionParse value_27 = parse;
            value = value_27.call(value_27.context, 1);
        }
        ordinal = (int32_t)((uint32_t)ordinal + 1u);
        if (value < 0) {
            (*(cursor->failed)) = 1;
            break;
        }
        InitializerField value_28 = field;
        int32_t child = value_28.call(value_28.context, field_start, name, named, value);
        if (child < 0) {
            break;
        }
        if (last >= 0) {
            ExpressionLink value_29 = link;
            value_29.call(value_29.context, last, child);
        } else {
            first = child;
        }
        last = child;
        bool value_30 = compiler_expression_Take(cursor, StringLiteral(","));
        if (!value_30) {
            break;
        }
    }
    compiler_expression_Expect(cursor, close);
    InitializerNode value_31 = node;
    return value_31.call(value_31.context, start, type, first);
}

int32_t
compiler_expression_ParsePrefix(PrefixHooks* hooks)
{
    SyntaxCursor* cursor = hooks->cursor;
    ExpressionToken token = cursor->token;
    ExpressionKind kind = cursor->kind;
    ExpressionBegin begin = cursor->begin;
    ExpressionAdvance advance = cursor->advance;
    ExpressionParse parse = cursor->parse;
    TypeQuery is_type = hooks->is_type;
    TypeQuery is_record = hooks->is_record;
    TypeQuery is_array = hooks->is_array;
    PrefixArray array = hooks->array;
    PrefixNode node = hooks->node;
    PrefixDiagnostic error = hooks->error;
    ExpressionBegin value_0 = begin;
    int64_t start = value_0.call(value_0.context);
    String original = compiler_expression_BorrowToken(cursor->source, cursor);
    ExpressionKind value_1 = kind;
    TokenKind original_kind = (TokenKind)(value_1.call(value_1.context));
    int32_t result = -1;
    (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) + 1u);
    if (*(cursor->depth) > 128) {
        (*(cursor->failed)) = 1;
        (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) - 1u);
        return -1;
    }
    if (compiler_expression_Take(cursor, StringLiteral("#this"))) {
        int64_t value_2 = (int64_t)(hooks->scope).length;
        if (value_2 == 0LL) {
            PrefixDiagnostic value_3 = error;
            value_3.call(value_3.context, PrefixError_ThisScope);
        }
        PrefixNode value_4 = node;
        result = value_4.call(value_4.context, start, PrefixKind_This, hooks->scope, StringLiteral(""), -1, -1, -1, 0);
    } else {
        ExpressionToken value_5 = token;
        if (StringEqual(value_5.call(value_5.context), StringLiteral("#caller_location"))) {
            PrefixDiagnostic value_6 = error;
            value_6.call(value_6.context, PrefixError_CallerLocation);
        } else if (compiler_expression_Take(cursor, StringLiteral("#compile_time"))) {
            PrefixNode value_7 = node;
            result = value_7.call(value_7.context, start, PrefixKind_CompileTime, StringLiteral(""), StringLiteral(""), -1, -1, -1, 0);
        } else if (compiler_expression_Take(cursor, StringLiteral("#procedure_name"))) {
            int64_t value_8 = (int64_t)(hooks->scope).length;
            if (value_8 == 0LL) {
                PrefixDiagnostic value_9 = error;
                value_9.call(value_9.context, PrefixError_ProcedureScope);
            }
            compiler_expression_Expect(cursor, StringLiteral("("));
            compiler_expression_Expect(cursor, StringLiteral(")"));
            PrefixNode value_10 = node;
            result = value_10.call(value_10.context, start, PrefixKind_ProcedureName, hooks->scope, StringLiteral(""), -1, -1, -1, 0);
        } else if (compiler_expression_Take(cursor, StringLiteral("#char"))) {
            ExpressionToken value_11 = token;
            int32_t byte = compiler_expression_CharacterByte(value_11.call(value_11.context));
            ExpressionKind value_12 = kind;
            bool value_13 = ((TokenKind)(value_12.call(value_12.context))) != ((TokenKind)(4));
            if (value_13 || byte < 0) {
                PrefixDiagnostic value_14 = error;
                value_14.call(value_14.context, PrefixError_Character);
            }
            ExpressionAdvance value_15 = advance;
            value_15.call(value_15.context);
            PrefixNode value_16 = node;
            result = value_16.call(value_16.context, start, PrefixKind_Character, StringLiteral(""), StringLiteral(""), -1, -1, -1, byte);
        } else {
            ExpressionToken value_17 = token;
            bool value_18 = StringEqual(value_17.call(value_17.context), StringLiteral("ifx"));
            bool value_19 = value_18;
            if (!value_19) {
                ExpressionToken value_20 = token;
                bool value_21 = StringEqual(value_20.call(value_20.context), StringLiteral("#ifx"));
                value_19 = value_21;
            }
            if (value_19) {
                String op = StringLiteral("ifx");
                ExpressionToken value_22 = token;
                if (StringEqual(value_22.call(value_22.context), StringLiteral("#ifx"))) {
                    op = StringLiteral("#ifx");
                }
                ExpressionAdvance value_23 = advance;
                value_23.call(value_23.context);
                ExpressionParse value_24 = parse;
                int32_t condition = value_24.call(value_24.context, 2);
                compiler_expression_Take(cursor, StringLiteral("then"));
                ExpressionParse value_25 = parse;
                int32_t selected = value_25.call(value_25.context, 1);
                compiler_expression_Take(cursor, StringLiteral(";"));
                compiler_expression_Expect(cursor, StringLiteral("else"));
                ExpressionParse value_26 = parse;
                int32_t alternative = value_26.call(value_26.context, 1);
                PrefixNode value_27 = node;
                result = value_27.call(value_27.context, start, PrefixKind_Conditional, StringLiteral(""), op, condition, selected, alternative, 0);
            } else {
                ExpressionToken value_28 = token;
                if (StringEqual(value_28.call(value_28.context), StringLiteral("sizeof"))) {
                    PrefixDiagnostic value_29 = error;
                    value_29.call(value_29.context, PrefixError_Sizeof);
                } else if (compiler_expression_Take(cursor, StringLiteral("size_of"))) {
                    compiler_expression_Expect(cursor, StringLiteral("("));
                    ExpressionBegin value_30 = begin;
                    int64_t type_start = value_30.call(value_30.context);
                    int32_t nested = 0;
                    while (true) {
                        ExpressionKind value_31 = kind;
                        if (!(((TokenKind)(value_31.call(value_31.context))) != ((TokenKind)(0)))) { break; }
                        ExpressionToken value_32 = token;
                        bool value_33 = StringEqual(value_32.call(value_32.context), StringLiteral(")"));
                        if (value_33 && nested == 0) {
                            break;
                        }
                        ExpressionToken value_34 = token;
                        if ((StringEqual(value_34.call(value_34.context), StringLiteral("(")))) {
                            nested = (int32_t)((uint32_t)nested + 1u);
                        }
                        ExpressionToken value_35 = token;
                        if ((StringEqual(value_35.call(value_35.context), StringLiteral(")")))) {
                            nested = (int32_t)((uint32_t)nested - 1u);
                        }
                        ExpressionAdvance value_36 = advance;
                        value_36.call(value_36.context);
                    }
                    String type = compiler_expression_TypeRange(cursor->source, cursor, type_start, hooks->name_limit);
                    compiler_expression_Expect(cursor, StringLiteral(")"));
                    PrefixNode value_37 = node;
                    result = value_37.call(value_37.context, start, PrefixKind_SizeOf, type, StringLiteral(""), -1, -1, -1, 0);
                } else if (compiler_expression_Take(cursor, StringLiteral("cast"))) {
                    compiler_expression_Expect(cursor, StringLiteral("("));
                    ExpressionBegin value_38 = begin;
                    int64_t type_start = value_38.call(value_38.context);
                    ExpressionToken value_39 = token;
                    if (StringEqual(value_39.call(value_39.context), StringLiteral("char"))) {
                        PrefixDiagnostic value_40 = error;
                        value_40.call(value_40.context, PrefixError_Primitive);
                    }
                    while (true) {
                        ExpressionKind value_41 = kind;
                        bool value_42 = ((TokenKind)(value_41.call(value_41.context))) != ((TokenKind)(0));
                        bool value_43 = value_42;
                        if (value_43) {
                            ExpressionToken value_44 = token;
                            bool value_45 = !StringEqual(value_44.call(value_44.context), StringLiteral(")"));
                            value_43 = value_45;
                        }
                        if (!value_43) { break; }
                        ExpressionAdvance value_46 = advance;
                        value_46.call(value_46.context);
                    }
                    String type = compiler_expression_TypeRange(cursor->source, cursor, type_start, hooks->name_limit);
                    TypeQuery value_47 = is_type;
                    bool value_48 = value_47.call(value_47.context, type);
                    bool value_49 = !value_48;
                    if (value_49) {
                        int64_t value_50 = (int64_t)(type).length;
                        bool value_51 = value_50 == 0LL;
                        if (!value_51) {
                            bool value_52 = (uint8_t)ZIRAN_INDEX(type.data, type.length, 0) != 91 && (uint8_t)ZIRAN_INDEX(type.data, type.length, 0) != 42;
                            value_51 = value_52;
                        }
                        value_49 = value_51;
                    }
                    if (value_49) {
                        (*(cursor->failed)) = 1;
                    }
                    compiler_expression_Expect(cursor, StringLiteral(")"));
                    int32_t right = compiler_expression_ParsePrefix(hooks);
                    PrefixNode value_53 = node;
                    result = value_53.call(value_53.context, start, PrefixKind_Cast, type, StringLiteral(""), -1, right, -1, 0);
                } else {
                    ExpressionToken value_54 = token;
                    bool value_55 = StringEqual(value_54.call(value_54.context), StringLiteral("++"));
                    bool value_56 = value_55;
                    if (!value_56) {
                        ExpressionToken value_57 = token;
                        bool value_58 = StringEqual(value_57.call(value_57.context), StringLiteral("--"));
                        value_56 = value_58;
                    }
                    if (value_56) {
                        PrefixDiagnostic value_59 = error;
                        value_59.call(value_59.context, PrefixError_Increment);
                    } else if (compiler_expression_Take(cursor, StringLiteral("<<"))) {
                        int32_t right = compiler_expression_ParsePrefix(hooks);
                        PrefixNode value_60 = node;
                        result = value_60.call(value_60.context, start, PrefixKind_Unary, StringLiteral(""), StringLiteral("*"), -1, right, -1, 0);
                    } else {
                        ExpressionToken value_61 = token;
                        bool value_62 = StringEqual(value_61.call(value_61.context), StringLiteral("+"));
                        bool value_63 = value_62;
                        if (!value_63) {
                            ExpressionToken value_64 = token;
                            bool value_65 = StringEqual(value_64.call(value_64.context), StringLiteral("-"));
                            value_63 = value_65;
                        }
                        bool value_66 = value_63;
                        if (!value_66) {
                            ExpressionToken value_67 = token;
                            bool value_68 = StringEqual(value_67.call(value_67.context), StringLiteral("!"));
                            value_66 = value_68;
                        }
                        bool value_69 = value_66;
                        if (!value_69) {
                            ExpressionToken value_70 = token;
                            bool value_71 = StringEqual(value_70.call(value_70.context), StringLiteral("~"));
                            value_69 = value_71;
                        }
                        bool value_72 = value_69;
                        if (!value_72) {
                            ExpressionToken value_73 = token;
                            bool value_74 = StringEqual(value_73.call(value_73.context), StringLiteral("*"));
                            value_72 = value_74;
                        }
                        if (value_72) {
                            ExpressionToken value_75 = token;
                            String op = compiler_expression_UnarySpelling(value_75.call(value_75.context));
                            ExpressionAdvance value_76 = advance;
                            value_76.call(value_76.context);
                            int32_t right = compiler_expression_ParsePrefix(hooks);
                            PrefixNode value_77 = node;
                            result = value_77.call(value_77.context, start, PrefixKind_Unary, StringLiteral(""), op, -1, right, -1, 0);
                        } else {
                            ExpressionToken value_78 = token;
                            if (StringEqual(value_78.call(value_78.context), StringLiteral("&"))) {
                                PrefixDiagnostic value_79 = error;
                                value_79.call(value_79.context, PrefixError_AddressOf);
                            } else if (compiler_expression_Take(cursor, StringLiteral("("))) {
                                TypeQuery value_80 = is_type;
                                ExpressionToken value_81 = token;
                                bool value_82 = value_80.call(value_80.context, value_81.call(value_81.context));
                                bool value_83 = value_82;
                                if (!value_83) {
                                    ExpressionToken value_84 = token;
                                    bool value_85 = StringEqual(value_84.call(value_84.context), StringLiteral("["));
                                    value_83 = value_85;
                                }
                                bool typed = value_83;
                                bool value_86 = typed;
                                if (value_86) {
                                    ExpressionToken value_87 = token;
                                    bool value_88 = !StringEqual(value_87.call(value_87.context), StringLiteral("."));
                                    value_86 = value_88;
                                }
                                bool value_89 = value_86;
                                if (value_89) {
                                    bool value_90 = !StringEqual(compiler_expression_Following(cursor->source, cursor, 1), StringLiteral("."));
                                    value_89 = value_90;
                                }
                                if (value_89) {
                                    PrefixDiagnostic value_91 = error;
                                    value_91.call(value_91.context, PrefixError_Cast);
                                }
                                ExpressionParse value_92 = parse;
                                result = value_92.call(value_92.context, 1);
                                compiler_expression_Expect(cursor, StringLiteral(")"));
                                bool value_93 = !typed;
                                if (value_93) {
                                    ExpressionToken value_94 = token;
                                    bool value_95 = StringEqual(value_94.call(value_94.context), StringLiteral("{"));
                                    value_93 = value_95;
                                }
                                if (value_93) {
                                    PrefixDiagnostic value_96 = error;
                                    value_96.call(value_96.context, PrefixError_Literal);
                                }
                            } else if (compiler_expression_Take(cursor, StringLiteral("."))) {
                                ExpressionToken value_97 = token;
                                if (StringEqual(value_97.call(value_97.context), StringLiteral("{"))) {
                                    result = compiler_expression_ParseInitializer(hooks->initializers, start, StringLiteral(""), StringLiteral("{"), StringLiteral("}"));
                                } else {
                                    ExpressionToken value_98 = token;
                                    bool value_99 = StringEqual(value_98.call(value_98.context), StringLiteral("["));
                                    bool value_100 = value_99;
                                    if (value_100) {
                                        TypeQuery value_101 = is_array;
                                        bool value_102 = value_101.call(value_101.context, hooks->expected_type);
                                        value_100 = value_102;
                                    }
                                    if (value_100) {
                                        result = compiler_expression_ParseInitializer(hooks->initializers, start, hooks->expected_type, StringLiteral("["), StringLiteral("]"));
                                    } else {
                                        ExpressionKind value_103 = kind;
                                        if (((TokenKind)(value_103.call(value_103.context))) != ((TokenKind)(1))) {
                                            (*(cursor->failed)) = 1;
                                        } else {
                                            uint8_t buffer[256] = {0};
                                            Slice value_104 = {buffer, 256};
                                            Slice value_105 = SliceRange(value_104, (int64_t)0, (int64_t)value_104.length, sizeof(uint8_t));
                                            String value_106 = compiler_expression_BorrowToken(cursor->source, cursor);
                                            String name = compiler_expression_QualifiedName(value_105, StringLiteral(""), value_106, hooks->name_limit);
                                            int64_t value_107 = (int64_t)(name).length;
                                            if (value_107 == 0LL) {
                                                (*(cursor->failed)) = 1;
                                            }
                                            ExpressionAdvance value_108 = advance;
                                            value_108.call(value_108.context);
                                            if (*(cursor->failed) == 0) {
                                                PrefixNode value_109 = node;
                                                result = value_109.call(value_109.context, start, PrefixKind_Identifier, name, StringLiteral(""), -1, -1, -1, 0);
                                            }
                                        }
                                    }
                                }
                            } else {
                                PrefixKind primary = (PrefixKind)(PrefixKind_Identifier);
                                if (original_kind == ((TokenKind)(2))) {
                                    primary = PrefixKind_Integer;
                                } else if (original_kind == ((TokenKind)(3))) {
                                    primary = PrefixKind_Float;
                                } else if (original_kind == ((TokenKind)(4))) {
                                    primary = PrefixKind_String;
                                } else if (original_kind == ((TokenKind)(5))) {
                                    PrefixDiagnostic value_110 = error;
                                    value_110.call(value_110.context, PrefixError_SingleQuote);
                                } else if (original_kind != ((TokenKind)(1))) {
                                    (*(cursor->failed)) = 1;
                                    (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) - 1u);
                                    return -1;
                                }
                                ExpressionAdvance value_111 = advance;
                                value_111.call(value_111.context);
                                bool value_112 = primary == PrefixKind_Identifier;
                                if (value_112) {
                                    ExpressionToken value_113 = token;
                                    bool value_114 = StringEqual(value_113.call(value_113.context), StringLiteral("."));
                                    value_112 = value_114;
                                }
                                if (value_112) {
                                    String following = compiler_expression_Following(cursor->source, cursor, 1);
                                    if (StringEqual(following, StringLiteral("{"))) {
                                        TypeQuery value_115 = is_record;
                                        bool value_116 = value_115.call(value_115.context, original);
                                        if (!value_116) {
                                            (*(cursor->failed)) = 1;
                                        }
                                        ExpressionAdvance value_117 = advance;
                                        value_117.call(value_117.context);
                                        result = compiler_expression_ParseInitializer(hooks->initializers, start, original, StringLiteral("{"), StringLiteral("}"));
                                    } else {
                                        bool value_118 = StringEqual(following, StringLiteral("["));
                                        if (value_118) {
                                            TypeQuery value_119 = is_type;
                                            bool value_120 = value_119.call(value_119.context, original);
                                            value_118 = value_120;
                                        }
                                        if (value_118) {
                                            ExpressionAdvance value_121 = advance;
                                            value_121.call(value_121.context);
                                            PrefixArray value_122 = array;
                                            result = value_122.call(value_122.context, start, original);
                                        } else {
                                            String value_123 = cursor->source;
                                            ExpressionBegin value_124 = begin;
                                            int64_t value_125 = value_124.call(value_124.context);
                                            ExpressionToken value_126 = token;
                                            String value_127 = value_126.call(value_126.context);
                                            Scan next = compiler_scan_NextToken(value_123, (int64_t)((uint64_t)value_125 + (uint64_t)((int64_t)(value_127).length)), 1, 1);
                                            bool value_128 = ((TokenKind)(next.kind)) == ((TokenKind)(1));
                                            if (value_128) {
                                                bool value_129 = StringEqual(compiler_expression_Following(cursor->source, cursor, 2), StringLiteral("."));
                                                value_128 = value_129;
                                            }
                                            if (value_128) {
                                                uint8_t buffer[256] = {0};
                                                Slice value_130 = {buffer, 256};
                                                String qualified = compiler_expression_QualifiedName(SliceRange(value_130, (int64_t)0, (int64_t)value_130.length, sizeof(uint8_t)), original, following, hooks->name_limit);
                                                String opener = compiler_expression_Following(cursor->source, cursor, 3);
                                                int64_t value_131 = (int64_t)(qualified).length;
                                                bool value_132 = value_131 > 0LL;
                                                if (value_132) {
                                                    TypeQuery value_133 = is_type;
                                                    bool value_134 = value_133.call(value_133.context, qualified);
                                                    value_132 = value_134;
                                                }
                                                if (value_132 && (StringEqual(opener, StringLiteral("[")) || StringEqual(opener, StringLiteral("{")))) {
                                                    ExpressionAdvance value_135 = advance;
                                                    value_135.call(value_135.context);
                                                    ExpressionAdvance value_136 = advance;
                                                    value_136.call(value_136.context);
                                                    ExpressionAdvance value_137 = advance;
                                                    value_137.call(value_137.context);
                                                    if (StringEqual(opener, StringLiteral("["))) {
                                                        PrefixArray value_138 = array;
                                                        result = value_138.call(value_138.context, start, qualified);
                                                    } else {
                                                        TypeQuery value_139 = is_record;
                                                        bool value_140 = value_139.call(value_139.context, qualified);
                                                        if (!value_140) {
                                                            (*(cursor->failed)) = 1;
                                                        } else {
                                                            result = compiler_expression_ParseInitializer(hooks->initializers, start, qualified, StringLiteral("{"), StringLiteral("}"));
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                                if (result < 0 && *(cursor->failed) == 0) {
                                    String name = StringLiteral("");
                                    if (primary == PrefixKind_Identifier) {
                                        name = original;
                                    }
                                    PrefixNode value_141 = node;
                                    result = value_141.call(value_141.context, start, primary, name, StringLiteral(""), -1, -1, -1, 0);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    result = compiler_expression_ParsePostfix(hooks->postfix, start, result);
    (*(cursor->depth)) = (int32_t)((uint32_t)((*(cursor->depth))) - 1u);
    return result;
}

int32_t
compiler_expression_CharacterByte(String literal)
{
    int64_t value_0 = (int64_t)(literal).length;
    bool value_1 = value_0 == 3LL && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 0) == 34 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 2) == 34;
    if (value_1 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1) < 128) {
        return (int32_t)((uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1));
    }
    int64_t value_2 = (int64_t)(literal).length;
    bool value_3 = value_2 == 4LL && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 0) == 34 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1) == 92;
    if (value_3 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 3) == 34) {
        uint8_t escape = (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 2);
        if (escape == 48) {
            return 0;
        }
        if (escape == 110) {
            return 10;
        }
        if (escape == 114) {
            return 13;
        }
        if (escape == 116) {
            return 9;
        }
        if (escape == 34) {
            return 34;
        }
        if (escape == 92) {
            return 92;
        }
        return -1;
    }
    int64_t value_4 = (int64_t)(literal).length;
    bool value_5 = value_4 == 6LL && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 0) == 34 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 1) == 92;
    if (value_5 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 2) == 120 && (uint8_t)ZIRAN_INDEX(literal.data, literal.length, 5) == 34) {
        int32_t high = compiler_expression_Hex((uint8_t)ZIRAN_INDEX(literal.data, literal.length, 3));
        int32_t low = compiler_expression_Hex((uint8_t)ZIRAN_INDEX(literal.data, literal.length, 4));
        if (high >= 0 && low >= 0) {
            return (int32_t)(((uint32_t)high * 16u) + (uint32_t)low);
        }
    }
    return -1;
}

StatementExpression
compiler_expression_StatementParts(String source, StatementKind kind)
{
    StatementExpression result = {0};
    bool value_0 = kind == ((StatementKind)(6));
    if (value_0) {
        bool value_1 = compiler_expression_WordAt(source, 0LL, StringLiteral("else"));
        value_0 = value_1;
    }
    result.is_else = value_0;
    if (kind == ((StatementKind)(3))) {
        int64_t colon = compiler_expression_FindByte(source, 58);
        if (colon >= 0LL) {
            result.has_declaration = true;
            String value_2 = source;
            result.name = compiler_expression_Trim(StringRange(value_2, (int64_t)0LL, (int64_t)colon));
            String value_3 = source;
            String type = StringRange(value_3, (int64_t)((int64_t)((uint64_t)colon + UINT64_C(1))), (int64_t)value_3.length);
            int64_t equals = compiler_expression_FindByte(type, 61);
            if (equals >= 0LL) {
                result.has_value = true;
                String value_4 = type;
                result.value = StringRange(value_4, (int64_t)((int64_t)((uint64_t)equals + UINT64_C(1))), (int64_t)value_4.length);
                String value_5 = type;
                type = StringRange(value_5, (int64_t)0LL, (int64_t)equals);
            }
            type = compiler_expression_Trim(type);
            int64_t value_6 = (int64_t)(type).length;
            bool value_7 = value_6 > 0LL;
            if (value_7) {
                bool value_8 = (uint8_t)ZIRAN_INDEX(type.data, type.length, ((int64_t)((uint64_t)((int64_t)(type).length) - UINT64_C(1)))) == 59;
                value_7 = value_8;
            }
            if (value_7) {
                String value_9 = type;
                type = compiler_expression_Trim(StringRange(value_9, (int64_t)0LL, (int64_t)((int64_t)((uint64_t)((int64_t)(type).length) - UINT64_C(1)))));
            }
            result.type = type;
            int64_t modifier = compiler_expression_FindByte(type, 35);
            if (modifier >= 0LL) {
                result.error = StatementExpressionError_Modifier;
                String value_10 = type;
                result.modifier = StringRange(value_10, (int64_t)modifier, (int64_t)value_10.length);
                return result;
            }
        }
    } else if (kind == ((StatementKind)(4))) {
        int64_t at = 0LL;
        while (true) {
            int64_t value_11 = (int64_t)(source).length;
            if (!(at < value_11)) { break; }
            Scan token = compiler_scan_NextToken(source, at, 1, 1);
            if (((TokenKind)(token.kind)) == ((TokenKind)(0))) {
                break;
            }
            String value_12 = source;
            String operator = StringRange(value_12, (int64_t)token.begin, (int64_t)token.end);
            if (compiler_expression_AssignmentOperator(operator)) {
                result.assignment = operator;
                String value_13 = source;
                result.lhs = StringRange(value_13, (int64_t)0LL, (int64_t)token.begin);
                String value_14 = source;
                result.value = StringRange(value_14, (int64_t)token.end, (int64_t)value_14.length);
                result.has_value = true;
                break;
            }
            at = token.end;
        }
    } else if (kind == ((StatementKind)(10)) || kind == ((StatementKind)(14))) {
        String keyword = StringLiteral("return");
        if (kind == ((StatementKind)(14))) {
            keyword = StringLiteral("unused");
        }
        int64_t value_15 = (int64_t)(source).length;
        int64_t value_16 = (int64_t)(keyword).length;
        if (value_15 >= value_16) {
            String value_17 = source;
            result.value = StringRange(value_17, (int64_t)(int64_t)(keyword).length, (int64_t)value_17.length);
            result.has_value = true;
        }
    } else if (kind == ((StatementKind)(5))) {
        result.value = source;
        result.has_value = true;
    } else if (kind == ((StatementKind)(16))) {
        int64_t value_18 = (int64_t)(source).length;
        if (value_18 >= 2LL) {
            String value_19 = source;
            String condition = compiler_expression_SkipSpace(StringRange(value_19, (int64_t)2LL, (int64_t)value_19.length));
            int64_t value_20 = (int64_t)(condition).length;
            bool value_21 = value_20 > 9LL;
            if (value_21) {
                String value_22 = condition;
                value_21 = (StringEqual(StringRange(value_22, (int64_t)0LL, (int64_t)9LL), StringLiteral("#complete")));
            }
            bool value_23 = value_21;
            bool value_24 = value_23;
            if (value_24) {
                bool value_25 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(condition.data, condition.length, 9));
                value_24 = value_25;
            }
            if (value_24) {
                String value_26 = condition;
                condition = compiler_expression_SkipSpace(StringRange(value_26, (int64_t)9LL, (int64_t)value_26.length));
            }
            int64_t equals = compiler_expression_FindPair(condition, StringLiteral("=="));
            if (equals >= 0LL) {
                String value_27 = condition;
                condition = compiler_expression_Trim(StringRange(value_27, (int64_t)0LL, (int64_t)equals));
            }
            result.value = condition;
            result.has_value = true;
        }
    } else if (kind == ((StatementKind)(7)) || kind == ((StatementKind)(6))) {
        String value_28 = source;
        int64_t value_29 = compiler_text_BlockHeaderEnd(source);
        String condition = StringRange(value_28, (int64_t)0LL, (int64_t)value_29);
        int64_t value_30 = (int64_t)(condition).length;
        bool value_31 = value_30 >= 4LL;
        if (value_31) {
            String value_32 = condition;
            value_31 = (StringEqual(StringRange(value_32, (int64_t)0LL, (int64_t)4LL), StringLiteral("else")));
        }
        if (value_31) {
            String value_33 = condition;
            condition = compiler_expression_SkipSpace(StringRange(value_33, (int64_t)4LL, (int64_t)value_33.length));
        }
        int64_t at = 0LL;
        while (true) {
            int64_t value_34 = (int64_t)(condition).length;
            bool value_35 = at < value_34;
            if (value_35) {
                bool value_36 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(condition.data, condition.length, at));
                value_35 = !value_36;
            }
            if (!(value_35 && (uint8_t)ZIRAN_INDEX(condition.data, condition.length, at) != 40)) { break; }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
        String value_37 = condition;
        result.value = StringRange(value_37, (int64_t)at, (int64_t)value_37.length);
        result.has_value = true;
    }
    bool value_38 = result.has_value;
    if (value_38) {
        bool value_39 = StringEqual(compiler_expression_SkipSpace(result.value), StringLiteral(";"));
        value_38 = value_39;
    }
    if (value_38) {
        result.has_value = false;
    }
    bool value_40 = result.has_value && kind == ((StatementKind)(3));
    if (value_40) {
        int64_t value_41 = (int64_t)(result.type).length;
        value_40 = (value_41 > 0LL);
    }
    if (value_40 && (uint8_t)ZIRAN_INDEX(result.type.data, result.type.length, 0) == 91) {
        String value = compiler_expression_SkipSpace(result.value);
        int64_t value_42 = (int64_t)(value).length;
        if (value_42 > 0LL && (uint8_t)ZIRAN_INDEX(value.data, value.length, 0) == 123) {
            result.error = StatementExpressionError_ArrayLiteral;
        }
    }
    return result;
}

static String
compiler_expression_UnarySpelling(String operator)
{
    if (StringEqual(operator, StringLiteral("*"))) {
        return StringLiteral("&");
    }
    if (StringEqual(operator, StringLiteral("+"))) {
        return StringLiteral("+");
    }
    if (StringEqual(operator, StringLiteral("-"))) {
        return StringLiteral("-");
    }
    if (StringEqual(operator, StringLiteral("!"))) {
        return StringLiteral("!");
    }
    return StringLiteral("~");
}

static String
compiler_expression_TypeRange(String source, SyntaxCursor* cursor, int64_t start, int64_t limit)
{
    ExpressionBegin begin = cursor->begin;
    ExpressionBegin value_0 = begin;
    int64_t end = value_0.call(value_0.context);
    bool value_1 = start < 0LL || end < start;
    if (!value_1) {
        int64_t value_2 = (int64_t)(source).length;
        value_1 = (end > value_2);
    }
    bool value_3 = value_1;
    if (!value_3) {
        int64_t value_4 = (int64_t)((uint64_t)end - (uint64_t)start);
        value_3 = (value_4 >= limit);
    }
    if (value_3) {
        (*(cursor->failed)) = 1;
        return StringLiteral("");
    }
    String value_5 = source;
    return compiler_expression_Trim(StringRange(value_5, (int64_t)start, (int64_t)end));
}

static String
compiler_expression_QualifiedName(Slice output, String first, String second, int64_t limit)
{
    int64_t count = (int64_t)(((uint64_t)((int64_t)(first).length) + UINT64_C(1)) + (uint64_t)((int64_t)(second).length));
    bool value_0 = count >= limit;
    if (!value_0) {
        int64_t value_1 = (int64_t)(output).length;
        value_0 = (count > value_1);
    }
    if (value_0) {
        return StringLiteral("");
    }
    {
        int64_t range_first_4 = 0LL;
        int64_t range_last_4 = (int64_t)((uint64_t)((int64_t)(first).length) - UINT64_C(1));
        int64_t index = range_first_4;
        while (index <= range_last_4) {
            ((uint8_t *)output.data)[SliceIndex(output, (int64_t)index)] = (uint8_t)ZIRAN_INDEX(first.data, first.length, index);
            if (index == range_last_4) {
                break;
            }
            index = (int64_t)((uint64_t)index + UINT64_C(1));
        }
    }
    ((uint8_t *)output.data)[SliceIndex(output, (int64_t)(int64_t)(first).length)] = 46;
    {
        int64_t range_first_8 = 0LL;
        int64_t range_last_8 = (int64_t)((uint64_t)((int64_t)(second).length) - UINT64_C(1));
        int64_t index = range_first_8;
        while (index <= range_last_8) {
            ((uint8_t *)output.data)[SliceIndex(output, (int64_t)((int64_t)(((uint64_t)((int64_t)(first).length) + UINT64_C(1)) + (uint64_t)index)))] = (uint8_t)ZIRAN_INDEX(second.data, second.length, index);
            if (index == range_last_8) {
                break;
            }
            index = (int64_t)((uint64_t)index + UINT64_C(1));
        }
    }
    Slice value_2 = output;
    Slice value_3 = SliceRange(value_2, (int64_t)0LL, (int64_t)count, sizeof(uint8_t));
    return StringView((const char *)(value_3).data, (size_t)(value_3).length);
}

static bool
compiler_expression_Take(SyntaxCursor* cursor, String wanted)
{
    ExpressionToken token = cursor->token;
    ExpressionAdvance advance = cursor->advance;
    ExpressionToken value_0 = token;
    if (!StringEqual(value_0.call(value_0.context), wanted)) {
        return false;
    }
    ExpressionAdvance value_1 = advance;
    value_1.call(value_1.context);
    return true;
}

static void
compiler_expression_Expect(SyntaxCursor* cursor, String wanted)
{
    bool value_0 = compiler_expression_Take(cursor, wanted);
    if (!value_0) {
        (*(cursor->failed)) = 1;
    }
}

static String
compiler_expression_BorrowToken(String source, SyntaxCursor* cursor)
{
    ExpressionBegin begin = cursor->begin;
    ExpressionToken token = cursor->token;
    ExpressionBegin value_0 = begin;
    int64_t at = value_0.call(value_0.context);
    ExpressionToken value_1 = token;
    String value_2 = value_1.call(value_1.context);
    int64_t count = (int64_t)(value_2).length;
    bool value_3 = at < 0LL;
    if (!value_3) {
        int64_t value_4 = (int64_t)(cursor->source).length;
        value_3 = (at > value_4);
    }
    bool value_5 = value_3;
    if (!value_5) {
        int64_t value_6 = (int64_t)((uint64_t)((int64_t)(cursor->source).length) - (uint64_t)at);
        value_5 = (count > value_6);
    }
    if (value_5) {
        (*(cursor->failed)) = 1;
        return StringLiteral("");
    }
    String value_7 = source;
    return StringRange(value_7, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + (uint64_t)count)));
}

static String
compiler_expression_Following(String source, SyntaxCursor* cursor, int32_t distance)
{
    ExpressionBegin begin = cursor->begin;
    ExpressionToken token = cursor->token;
    ExpressionBegin value_0 = begin;
    int64_t value_1 = value_0.call(value_0.context);
    ExpressionToken value_2 = token;
    String value_3 = value_2.call(value_2.context);
    int64_t at = (int64_t)((uint64_t)value_1 + (uint64_t)((int64_t)(value_3).length));
    Scan following = {0};
    {
        int32_t range_first_4 = 1;
        int32_t range_last_4 = distance;
        int32_t index = range_first_4;
        while (index <= range_last_4) {
            following = compiler_scan_NextToken(cursor->source, at, 1, 1);
            at = following.end;
            if (index == range_last_4) {
                break;
            }
            index = (int32_t)((uint32_t)index + 1u);
        }
    }
    String value_4 = source;
    return StringRange(value_4, (int64_t)following.begin, (int64_t)following.end);
}

static int32_t
compiler_expression_Hex(uint8_t byte)
{
    if (byte >= 48 && byte <= 57) {
        return (int32_t)(((uint8_t)((uint32_t)byte - 48u)));
    }
    if (byte >= 65 && byte <= 70) {
        return (int32_t)((uint32_t)(((uint8_t)((uint32_t)byte - 65u))) + 10u);
    }
    if (byte >= 97 && byte <= 102) {
        return (int32_t)((uint32_t)(((uint8_t)((uint32_t)byte - 97u))) + 10u);
    }
    return -1;
}

static String
compiler_expression_Trim(String source)
{
    SourceRange range = compiler_text_TrimRange(source);
    String value_0 = source;
    return StringRange(value_0, (int64_t)range.begin, (int64_t)range.end);
}

static String
compiler_expression_SkipSpace(String source)
{
    String value_0 = source;
    SourceRange value_1 = compiler_text_TrimRange(source);
    return StringRange(value_0, (int64_t)value_1.begin, (int64_t)value_0.length);
}

static int64_t
compiler_expression_FindByte(String source, uint8_t wanted)
{
    {
        int64_t range_first_0 = 0LL;
        int64_t range_last_0 = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(1));
        int64_t at = range_first_0;
        while (at <= range_last_0) {
            if ((uint8_t)ZIRAN_INDEX(source.data, source.length, at) == wanted) {
                return at;
            }
            if (at == range_last_0) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return -1LL;
}

static int64_t
compiler_expression_FindPair(String source, String wanted)
{
    {
        int64_t range_first_0 = 0LL;
        int64_t range_last_0 = (int64_t)((uint64_t)((int64_t)(source).length) - UINT64_C(2));
        int64_t at = range_first_0;
        while (at <= range_last_0) {
            String value_0 = source;
            if (StringEqual(StringRange(value_0, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + UINT64_C(2)))), wanted)) {
                return at;
            }
            if (at == range_last_0) {
                break;
            }
            at = (int64_t)((uint64_t)at + UINT64_C(1));
        }
    }
    return -1LL;
}

static bool
compiler_expression_WordAt(String source, int64_t at, String word)
{
    bool value_0 = at >= 0LL;
    if (value_0) {
        int64_t value_1 = (int64_t)(word).length;
        int64_t value_2 = (int64_t)((uint64_t)((int64_t)(source).length) - (uint64_t)at);
        value_0 = (value_1 <= value_2);
    }
    bool value_3 = value_0;
    if (value_3) {
        String value_4 = source;
        bool value_5 = StringEqual(StringRange(value_4, (int64_t)at, (int64_t)((int64_t)((uint64_t)at + (uint64_t)((int64_t)(word).length)))), word);
        value_3 = value_5;
    }
    bool value_6 = value_3;
    bool value_7 = value_6;
    if (value_7) {
        int64_t value_8 = (int64_t)((uint64_t)at + (uint64_t)((int64_t)(word).length));
        int64_t value_9 = (int64_t)(source).length;
        bool value_10 = value_8 == value_9;
        if (!value_10) {
            bool value_11 = compiler_text_SpaceByte((uint8_t)ZIRAN_INDEX(source.data, source.length, ((int64_t)((uint64_t)at + (uint64_t)((int64_t)(word).length)))));
            value_10 = value_11;
        }
        value_7 = value_10;
    }
    return value_7;
}

static bool
compiler_expression_AssignmentOperator(String operator)
{
    bool value_0 = StringEqual(operator, StringLiteral("=")) || StringEqual(operator, StringLiteral("+=")) || StringEqual(operator, StringLiteral("-="));
    bool value_1 = value_0 || StringEqual(operator, StringLiteral("*=")) || StringEqual(operator, StringLiteral("/="));
    bool value_2 = value_1 || StringEqual(operator, StringLiteral("%=")) || StringEqual(operator, StringLiteral("&="));
    bool value_3 = value_2 || StringEqual(operator, StringLiteral("|=")) || StringEqual(operator, StringLiteral("^="));
    return value_3 || StringEqual(operator, StringLiteral("<<=")) || StringEqual(operator, StringLiteral(">>="));
}
