/* Generated by zi2c from compiler_type.zi. */
#ifndef ZIRAN_COMPILER_TYPE_H
#define ZIRAN_COMPILER_TYPE_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_slice.h"
#include "zir_string.h"
#include "compiler_text.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef struct RecordField RecordField;
typedef struct ElementType ElementType;
typedef struct ForeignCall ForeignCall;

struct RecordField {
    int32_t status;
    int64_t next;
    String name;
    String type;
    String tag;
    bool is_using;
};

struct ElementType {
    bool valid;
    String element;
    int64_t capacity;
};

struct ForeignCall {
    int32_t kind;
    String module;
    String receiver;
    String symbol;
};
bool compiler_type_TargetKnown(String target);
String compiler_type_ForeignTypeTarget(String foreign, bool is_map);
bool compiler_type_ForeignImportSupported(String target, String foreign);
bool compiler_type_ProcedureTypeSupported(String target, bool c_call);
int32_t compiler_type_ScalarByteWidth(String type);
RecordField compiler_type_NextField(String body, int64_t at, bool union_record, int64_t name_limit, int64_t type_limit, Slice tag_workspace);
ElementType compiler_type_SliceElement(String type);
ElementType compiler_type_ArrayElement(String type);
bool compiler_type_BuiltinName(String name);
bool compiler_type_MapPrimitive(String name);
ForeignCall compiler_type_GoCall(String target, int64_t receiver_limit);
bool compiler_type_GoTypeTarget(String target);
ForeignCall compiler_type_PythonCall(String target);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_TYPE_H */
