/* Generated by zi2c from compiler_declaration.zi. */
#ifndef ZIRAN_COMPILER_DECLARATION_H
#define ZIRAN_COMPILER_DECLARATION_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "zir_bounds.h"
#include "zir_slice.h"
#include "zir_string.h"
#include "compiler_text.h"
#include "compiler_source.h"
#include "compiler_scan.h"

#ifdef __cplusplus
extern "C" {
#endif
typedef int32_t DeclarationError;
typedef struct GoMethodDeclaration GoMethodDeclaration;
typedef struct ExportDirective ExportDirective;
typedef struct ParameterRewrite ParameterRewrite;
typedef int32_t ImportMode;
typedef struct ModuleImport ModuleImport;
typedef struct LibraryDeclaration LibraryDeclaration;
typedef struct MethodSymbol MethodSymbol;
typedef struct UsingFilter UsingFilter;
typedef struct ForeignDeclaration ForeignDeclaration;
typedef struct ForeignTarget ForeignTarget;
typedef struct ResultDeclaration ResultDeclaration;
typedef struct ResultReturn ResultReturn;
typedef struct ResultBinding ResultBinding;
typedef struct SymmetricRewrite SymmetricRewrite;
typedef struct TextRewrite TextRewrite;
typedef struct NameReplacement NameReplacement;
typedef struct PrintRewrite PrintRewrite;
typedef struct StatementOutput StatementOutput;
#ifdef ZIRAN_COMPILER_DECLARATION_H_PRIVATE
typedef struct QuotedText QuotedText;
#endif

enum {
    DeclarationError_None = 0,
    DeclarationError_ExportQuote = 1,
    DeclarationError_ExportName = 2,
    DeclarationError_Parameters = 3,
    DeclarationError_DefaultValue = 4,
    DeclarationError_UsingModifier = 5,
    DeclarationError_UsingType = 6,
    DeclarationError_UsingName = 7,
    DeclarationError_ImportQuote = 8,
    DeclarationError_ImportCharacter = 9,
    DeclarationError_ImportMode = 10,
    DeclarationError_ImportDirSyntax = 11,
    DeclarationError_ImportDirPath = 12,
    DeclarationError_ImportDirName = 13,
    DeclarationError_ImportFileSyntax = 14,
    DeclarationError_ImportFilePath = 15,
    DeclarationError_ImportFileName = 16,
    DeclarationError_ImportAlias = 17,
    DeclarationError_ImportTarget = 18,
    DeclarationError_ImportPackage = 19,
    DeclarationError_ImportUsing = 20,
    DeclarationError_LibraryQuote = 21,
    DeclarationError_LibraryEnd = 22,
    DeclarationError_LibraryCharacter = 23,
    DeclarationError_UsingKind = 24,
    DeclarationError_UsingList = 25,
    DeclarationError_UsingEntry = 26,
    DeclarationError_UsingMap = 27,
    DeclarationError_ForeignResults = 28,
    DeclarationError_ForeignField = 29,
    DeclarationError_ForeignDefer = 30,
    DeclarationError_ForeignVariadic = 31,
    DeclarationError_ForeignPythonAttributes = 32,
    DeclarationError_ForeignType = 33,
    DeclarationError_ForeignBody = 34,
    DeclarationError_ForeignLibrary = 35,
    DeclarationError_ForeignSymbol = 36,
    DeclarationError_ForeignEnd = 37,
    DeclarationError_ForeignPythonSymbol = 38,
    DeclarationError_ForeignHostRename = 39,
    DeclarationError_ForeignGoResults = 40,
    DeclarationError_ForeignGoField = 41,
    DeclarationError_ForeignGoDefer = 42,
    DeclarationError_ForeignGoVariadic = 43,
    DeclarationError_ForeignPythonResults = 44,
    DeclarationError_ForeignPythonField = 45,
    DeclarationError_ResultCount = 46,
    DeclarationError_ResultName = 47,
    DeclarationError_ResultType = 48,
    DeclarationError_ResultParameters = 49,
    DeclarationError_ReturnCount = 50,
    DeclarationError_SymmetricParameters = 51,
    DeclarationError_SymmetricModifier = 52,
    DeclarationError_ProcedureNameArguments = 53,
    DeclarationError_BuilderFormat = 54,
    DeclarationError_BuilderPercent = 55,
    DeclarationError_BuilderArguments = 56,
    DeclarationError_BuilderPieces = 57,
    DeclarationError_BuilderArgumentCount = 58,
    DeclarationError_GoMethodQuote = 59,
    DeclarationError_GoMethodDuplicate = 60,
    DeclarationError_GoMethodResults = 61,
    DeclarationError_GoMethodForeign = 62,
    DeclarationError_ProcedureTypeCount = 63,
    DeclarationError_ProcedureTypeName = 64,
    DeclarationError_ProcedureTypeType = 65,
    DeclarationError_ProcedureTypeDefault = 66,
};

struct GoMethodDeclaration {
    DeclarationError error;
    String name;
    bool results;
};

struct ExportDirective {
    DeclarationError error;
    int32_t kind;
    String symbol;
    String body;
};

struct ParameterRewrite {
    DeclarationError error;
    int64_t count;
    int32_t parameters;
    bool has_defaults;
    uint64_t using_parameters;
};

enum {
    ImportMode_Module = 0,
    ImportMode_File = 1,
    ImportMode_Directory = 2,
};

struct ModuleImport {
    DeclarationError error;
    bool present;
    bool named;
    bool using_import;
    ImportMode mode;
    String name;
    String target;
    String path;
    String detail;
};

struct LibraryDeclaration {
    DeclarationError error;
    bool present;
    String name;
    String target;
};

struct MethodSymbol {
    bool valid;
    String receiver;
    String method;
};

struct UsingFilter {
    DeclarationError error;
    bool present;
    int64_t count;
    int64_t next;
};

struct ForeignDeclaration {
    DeclarationError error;
    bool present;
    String name;
    String library;
    String symbol;
    bool is_type;
    bool go_results;
    bool go_field;
    bool go_defer;
    bool go_variadic;
    bool py_results;
    bool py_field;
};

struct ForeignTarget {
    DeclarationError error;
    int64_t count;
};

struct ResultDeclaration {
    DeclarationError error;
    int32_t count;
    String types[16];
    int32_t parameter_count;
    String parameters[64];
};

struct ResultReturn {
    DeclarationError error;
    bool present;
    int32_t values;
    int64_t count;
};

struct ResultBinding {
    bool present;
    int32_t count;
    bool inferred;
    String targets[16];
    String value;
};

struct SymmetricRewrite {
    DeclarationError error;
    bool present;
    bool needed;
    int64_t header_count;
    int64_t count;
};

struct TextRewrite {
    DeclarationError error;
    bool changed;
    int64_t count;
};

struct NameReplacement {
    String source;
    String target;
};

struct PrintRewrite {
    DeclarationError error;
    int32_t statements;
    int64_t lengths[64];
};

struct StatementOutput {
    Slice bytes;
};
#ifdef ZIRAN_COMPILER_DECLARATION_H_PRIVATE

struct QuotedText {
    bool valid;
    String value;
    int64_t end;
};
#endif
String compiler_declaration_ErrorText(DeclarationError error);
GoMethodDeclaration compiler_declaration_ParseGoMethod(String source, int64_t name_limit);
UsingFilter compiler_declaration_UsingModifierClause(String source, Slice output, int64_t name_limit);
ExportDirective compiler_declaration_ProgramExport(String source, int64_t symbol_limit);
ParameterRewrite compiler_declaration_RewriteParameters(String source, Slice output, bool strip_defaults, bool strip_using, int64_t name_limit);
ParameterRewrite compiler_declaration_RewriteProcedureTypeParameters(String source, Slice output, int64_t name_limit);
ModuleImport compiler_declaration_ImportDeclaration(String source, int64_t name_limit, int64_t path_limit);
LibraryDeclaration compiler_declaration_SystemLibrary(String source, int64_t name_limit, int64_t path_limit);
MethodSymbol compiler_declaration_ForeignMethod(String source, int64_t receiver_limit, int64_t method_limit, bool python);
bool compiler_declaration_PythonAttribute(String source, int64_t name_limit);
ForeignDeclaration compiler_declaration_ParseForeign(String source, int64_t name_limit);
ForeignTarget compiler_declaration_ResolveForeignTarget(ForeignDeclaration declaration, String library, Slice output, int64_t name_limit);
bool compiler_declaration_ForeignVarargs(String parameters);
ResultDeclaration compiler_declaration_ParseResults(String source, String template_parameters);
int64_t compiler_declaration_ResultsRecord(ResultDeclaration results, Slice output);
int64_t compiler_declaration_ResultsParameters(ResultDeclaration results, Slice output);
int64_t compiler_declaration_ResultsBody(ResultDeclaration results, Slice output);
ResultReturn compiler_declaration_RewriteResultReturn(String source, String record, int32_t results, Slice output);
ResultBinding compiler_declaration_MultipleBinding(String source, int32_t maximum, int64_t name_limit);
bool compiler_declaration_DefaultScopeIndependent(String source, int64_t token_limit);
TextRewrite compiler_declaration_RewriteProcedureName(String source, String name, Slice output);
TextRewrite compiler_declaration_RewriteLocalNames(String source, Slice names, Slice output);
SymmetricRewrite compiler_declaration_RewriteSymmetric(String source, Slice header_output, Slice wrapper_output, int64_t name_limit);
PrintRewrite compiler_declaration_BuilderPrintPieces(String source, Slice output, int32_t maximum);

#ifdef __cplusplus
}
#endif

#endif /* ZIRAN_COMPILER_DECLARATION_H */
